### PR TITLE
Fix pytorch version >= 1.2

### PR DESCRIPTION
**Pull request by sdesrozis**
Description:

Fix for Pytorch >= 1.2

Check list:
* [ ] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by sdesrozis** [comment]
My nightly work was useful 👍🏻

**Comment by vfdev-5** [comment]
Could you please take a look it again : https://github.com/pytorch/ignite/actions/runs/127256968 ?

**Comment by sdesrozis** [comment]
Not possible to rerun ?

**Comment by vfdev-5** [comment]
I can rerun on the same commit

**Pull request merged**
