### PR TITLE
update pytest match and edit tests

### PR DESCRIPTION
**Pull request by KickItLikeShika**
I though it would be nice to add `match` to `pytest.raises()` in `ignite.contrib.metrics.regression`. And updated some tests' names. `test_zero_div` wasn't a proper name for some tests, edited it to `test_zero_sample`
Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Review by vfdev-5 — COMMENTED** [review]
Thanks for the PR @KickItLikeShika !

We have to repair "Run Horovod tests" before merging this PR as there was versions update today.

**Comment by KickItLikeShika** [comment]
@vfdev-5 Do i have to edit anything or just wait?

**Comment by vfdev-5** [comment]
If you could inspect what is the exact issue here : https://github.com/pytorch/ignite/pull/1746/checks?check_run_id=2041788241
it could help.

**Review by vfdev-5 — APPROVED** [review]

**Comment by vfdev-5** [comment]
Looks like the failure is flaky and more or less cna be ignored now. I'll merge the PR once CI is done.
Thanks again @KickItLikeShika !

**Pull request merged**
