### PR TITLE
New metric ConfusionMatrix, IoU, mean IoU 

### PR DESCRIPTION
**Pull request by vfdev-5**
Description:
In this PR new metrics : ConfusionMatrix, IoU, mIoU etc are proposed into core module.

Check list:
* [x] New tests are added (if a new feature is added)
* [x] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by TheCodez** [comment]
@vfdev-5 do I have to attach ConfusionMatrix or mIoU to the trainer?

**Comment by vfdev-5** [comment]
@TheCodez this should work as ordinary metric, I guess :)

**Comment by TheCodez** [comment]
@vfdev-5 thanks, so this usage would be correct?

```python
cm = ConfusionMatrix(num_classes=num_classes, output_transform=lambda x: x['semantics'])
mIoU(cm, ignore_index=0).attach(train_evaluator, 'mIoU')
```

**Comment by vfdev-5** [comment]
@TheCodez yep. Tell me if it does not work as intended :)

**Pull request merged**
