### PR TITLE
Fix hostname list expansion

### LINKED ISSUE #2203: Bug with `_expand_nodelist`
## 🐛 Bug description

```
_expand_hostlist('gpu-compute-on-demand-dy-g4dnxlarge-[1-4]')
> 
['g4dnxlarge-1', 'g4dnxlarge-2', 'g4dnxlarge-3', 'g4dnxlarge-4']
```
but should be
```
scontrol show hostnames 'gpu-compute-on-demand-dy-g4dnxlarge-[1-4]'
>
gpu-compute-on-demand-dy-g4dnxlarge-1
gpu-compute-on-demand-dy-g4dnxlarge-2
gpu-compute-on-demand-dy-g4dnxlarge-3
gpu-compute-on-demand-dy-g4dnxlarge-4
```

## Environment

- PyTorch Version (e.g., 1.4):
- Ignite Version (e.g., 0.3.0): 0.4.6
- OS (e.g., Linux):
- How you installed Ignite (`conda`, `pip`, source):
- Python version:
- Any other relevant information:

cc @sdesrozis

### PR DESCRIPTION
**Pull request by sdesrozis**
Fixes #2203

Description:

See #2048 discussion.

Fix hostname list expansion.

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@sdesrozis thanks for the fix. I was playing a bit more with `scontrol show hostnames` and it behaves a bit differently vs `_expand_hostlist`.
1) Other specific symbols: `+`, `:` etc

```
scontrol show hostnames "compute+b24_[1-2]"
compute+b24_1
compute+b24_2

scontrol show hostnames "compute:b24_[1-2]"
compute:b24_1
compute:b24_2
```
but
```
_expand_hostlist("compute:b24_[1-2]")
['compute', 'b24_1', 'b24_2']

_expand_hostlist("compute+b24_[1-2]")
['compute', 'b24_1', 'b24_2']
```

2) Overlapping hosts
```
scontrol show hostnames "overlapping-hosts_[1-3,2-4]"
overlapping-hosts_1
overlapping-hosts_2
overlapping-hosts_3
overlapping-hosts_2
overlapping-hosts_3
overlapping-hosts_4
```
but
```
_expand_hostlist("overlapping-hosts_[1-3,2-4]")
[
 'overlapping-hosts_1',
 'overlapping-hosts_2',
 'overlapping-hosts_3',
 'overlapping-hosts_4'
]
```
Maybe, this is less important as we take only the first one.

**Comment by sdesrozis** [comment]
> ```
> scontrol show hostnames "compute+b24_[1-2]"
> compute+b24_1
> compute+b24_2
> 
> scontrol show hostnames "compute:b24_[1-2]"
> compute:b24_1
> compute:b24_2
> ```

I agree I did the minimum.

> ```
> scontrol show hostnames "overlapping-hosts_[1-3,2-4]"
> overlapping-hosts_1
> overlapping-hosts_2
> overlapping-hosts_3
> overlapping-hosts_2
> overlapping-hosts_3
> overlapping-hosts_4
> ```
> 
> but
> 
> ```
> _expand_hostlist("overlapping-hosts_[1-3,2-4]")
> [
>  'overlapping-hosts_1',
>  'overlapping-hosts_2',
>  'overlapping-hosts_3',
>  'overlapping-hosts_4'
> ]
> ```

I think our version is better. Anyway, it does not really matter.

**Comment by vfdev-5** [comment]
Another example for multiple expansions:
```
scontrol show hostnames "compute[2,3]b24[1,2]"
compute2b241
compute2b242
compute3b241
compute3b242
```
but we output
```
_expand_hostlist("compute[2,3]b24[1,2]")

['compute2b24', 'compute3b24', '1', '2']
```

**Comment by sdesrozis** [comment]
> Another example for multiple expansions:
> 
> ```
> scontrol show hostnames "compute[2,3]b24[1,2]"
> compute2b241
> compute2b242
> compute3b241
> compute3b242
> ```
> 
> but we output
> 
> ```
> _expand_hostlist("compute[2,3]b24[1,2]")
> 
> ['compute2b24', 'compute3b24', '1', '2']
> ```

Not supported at the moment. It means refactor deeply the implementation.

**Comment by sdesrozis** [comment]
Every char is legal except the special ones `[`, `]`, `,` to build the host names. However, only one sequence `[...]` per host name is supported.

**Review by vfdev-5 — APPROVED** [review]
Thanks for the fix @sdesrozis !

**Pull request merged**
