### PR TITLE
ValueError -> TypeError

### PR DESCRIPTION
**Pull request by WrRan**
Fixes # 

Description:
>`TypeError` may be raised when an operation or function is applied to an object of an inappropriate type, while `ValueError` may be raised when an operation or function receives an argument that has the right type but an inappropriate value.
>
> @ python at https://docs.python.org/3/library/exceptions.html

Thus, `TypeError` is preferred over `ValueError` here.

Check list:
* [ ] New tests are added (if a new feature is added)
* [x] New doc strings: description and/or example code are in RST format
* [x] Documentation is updated (if required)

### CODE REVIEW

**Comment by sdesrozis** [comment]
@WrRan Thank you ! Good catch !

Could you look a bit deeper to check if there are others misusing ? It would help a lot 😊 

Tests are ko because we catch the exception type and test it. I think that tests should be updated.

Thanks again 🙏🏻

**Comment by vfdev-5** [comment]
@WrRan the following test is failing as it checks for `ValueError` instead of `TypeError`: https://travis-ci.org/github/pytorch/ignite/jobs/704562160#L2316
Could you please adapt it accordingly. Thanks!

**Comment by WrRan** [comment]
Got it. I am working on it. :-)

**Comment by WrRan** [comment]
@sean-adler 
I have gone through the codebase and found there is a wide spectrum of misuses of exceptions in lots of files (such as `NotImplemented` and `NotImplementedError` see #1178  and `RuntimeError` and `TypeError` see https://github.com/pytorch/ignite/blob/master/ignite/contrib/handlers/polyaxon_logger.py#L104 etc.)

To make matter worse, there are some situations we should divide one exception into more than one. For example, in https://github.com/pytorch/ignite/blob/master/ignite/contrib/handlers/param_scheduler.py#L860, the `ValueError` should be one `TypeError` and one `Value`.

This situation makes not only refactor code hard but also code review not easy.

So, I think it is a better idea to work on this problem one by one file through many PRs rather than all of them at one time. What do you think?

**Comment by vfdev-5** [comment]
@WrRan thanks for pointing out those things. Fixing those incoherent with python best-practices exception is not a priority, but if you would like to make our codebase perfect, feel free to send PRs with fixed code and adapted test. Thanks !

**Pull request merged**
