### PR TITLE
Added PiecewiseLinear param scheduler

### PR DESCRIPTION
**Pull request by vfdev-5**
Description:
New feature "PiecewiseLinear" parameter scheduler. This implementation allows easily to schedule a parameter without pain of concat + linear cyclic.
```python
scheduler = PiecewiseLinear(optimizer, "lr", values=[0.5, 0.45, 0.3, 0.1, 0.1], milestones=[10, 20, 21, 30, 40])
```
image

```python
milestones=[0,4,4,25,25,30,30,35] 
values=[0.0,0.4,0.3,0.3,0.03,0.03,0.003,0.0]
lr_values = PiecewiseLinear.simulate_values(num_events=35, param_name="lr", values=values, milestones=milestones)
```
image

Check list:
* [x] New tests are added (if a new feature is modified)
* [x] New doc strings: text and/or example code are in RST format
* [x] Documentation is updated (if required)

### CODE REVIEW

**Comment by jasonkriss** [comment]
👍 LGTM. One thing... Do you maybe want to combine values and milestones into a single list of tuples? Might help prevent having mismatched lengths and can be easier to see when each value is reached at a glance.

**Comment by vfdev-5** [comment]
@jasonkriss yes, that's a good idea, but we need then assert somehow that such `values_milestones` list contains pairs and the milestones are ordered. I did not find a simple and nice way to check that without for loop and etc. 
Maybe we could give another try for this idea. How would you call that argument (`values_milestones`) ?

**Comment by jasonkriss** [comment]
Yea I see you're point. Honestly, I don't feel super strongly about it. Maybe it's best to just keep it as you have it?

**Comment by vfdev-5** [comment]
@anmolsjoshi @jasonkriss Added new API with `milestones_values`:
```python
milestones_values=[(0, 0.0), (4, 0.4), (4, 0.3), (25, 0.3), (25, 0.03), (30, 0.03), (30, 0.003), (35, 0.0)] 
lr_values = PiecewiseLinear.simulate_values(num_events=35, param_name="lr", milestones_values=milestones_values)
```

What do you think ?

**Comment by jasonkriss** [comment]
@vfdev-5 👍I like it!

**Comment by vfdev-5** [comment]
@jasonkriss , @anmolsjoshi @alykhantejani if this PR is OK, please merge it

**Pull request merged**
