### PR TITLE
Added docker image test script

### PR DESCRIPTION
**Pull request by vfdev-5**
Addresses #1644

Description:
- Added docker image test python script

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by trsvchn** [comment]
there is python package docker? Nice!)

Since, I've started from `subprocess.run` :)

**Comment by vfdev-5** [comment]
Yes, I tried that from my side to see if this could work. @trsvchn if you'd like to review, feel free to comment out and give a feedback.

**Comment by vfdev-5** [comment]
And sorry for overlapping !

**Comment by trsvchn** [comment]
No problem, sorry, I was busy yesterday. and now I know about `docker` python so it worth it :)

**Comment by vfdev-5** [comment]
@trsvchn do you have an idea why it can't find installed `docker` package ?

**Comment by trsvchn** [comment]
@vfdev-5 Oh, I think I know what is happening

**Comment by trsvchn** [comment]
` $AGENT_TOOLSDIRECTORY` is `/opt/hostedtoolcache` 

and

```bash
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.10/x64/lib
```

Thus:

```bash
sudo rm -rf "/usr/local/share/boost"
sudo rm -rf "$AGENT_TOOLSDIRECTORY"
```
Removes python libs

**Comment by vfdev-5** [comment]
Oh, I see. Should we just reinstall it after building ?

**Comment by trsvchn** [comment]
But, wait, pyaml works fine

**Comment by vfdev-5** [comment]
pyyaml is OK as it is used only before the suppression

**Comment by trsvchn** [comment]
Yes, for base images
but we reuse it in later steps

**Comment by trsvchn** [comment]
Let's try 

```
sudo rm -rf "/usr/local/share/boost"
sudo rm -rf "$AGENT_TOOLSDIRECTORY"
```

Just after the checkout, and before Python install actiob

**Comment by vfdev-5** [comment]
@trsvchn seems like it works !

**Comment by trsvchn** [comment]
Great!

**Comment by vfdev-5** [comment]
@trsvchn I'm struggling with `test_image.py` script and the way how to expose details of the error when using docker python api. For example, here https://github.com/pytorch/ignite/pull/1733/checks?check_run_id=2046167278#step:6:605
import command is failing but we have no idea what is the error message. 
Basically, the following code is missing something.
```python
def run_python_cmd(cmd):
    try:
        out = client.containers.run(args.image, f"python -c '{cmd}'", auto_remove=True, stderr=True,)
        assert isinstance(out, bytes), type(out)
        out = out.decode("utf-8").strip()
    except docker.errors.ContainerError as e:
        raise RuntimeError(e)
    return out
```
Any ideas how to improve it ?

**Comment by trsvchn** [comment]
@vfdev-5 sure! I'll test `test_image.py` in my sandbox

**Comment by vfdev-5** [comment]
I'm thinking to do something like 
```python
def run_python_cmd(cmd):

    try_except_cmd = f"""

def main():
    {cmd}

try:
    main()
except Exception as e:
    import traceback
    print(traceback.format_exc())    
    """
    try:
        out = client.containers.run(args.image, f"python -c '{try_except_cmd}'", auto_remove=True, stderr=True,)
        assert isinstance(out, bytes), type(out)
        out = out.decode("utf-8").strip()

        if any([k in out.lower() for k in ["error", "exception"]]):
            raise RuntimeError(out)

    except docker.errors.ContainerError as e:
        raise RuntimeError(e)
    return out
```

but this looks like a hack...

**Comment by trsvchn** [comment]
@vfdev-5 Yes!, I think the problem is in that we are raising exceptions, since this generates exit code 1 and it forces run method to raise exception:

```bash
$ python -c 'raise RuntimeError'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError

$ echo $?
1
```

>         Raises:
>             :py:class:`docker.errors.ContainerError`
>                 If the container exits with a non-zero exit code and

we should handle this quietly

**Comment by vfdev-5** [comment]
That's right. But what I'd like to have is to execute tests like `import cv2` and ensure that it passes and if not say that explicitly : "ModuleNotFoundError: No module named 'c2'".
I was just thinking if there is a proper way to get error message without 2 levels of exception trackings

**Comment by trsvchn** [comment]
What about to try `detach=True`, with this param, run method returns logs:

>            If ``detach`` is ``True``, a :py:class:`Container` object is instead.

```python
container = client.containers.run('bfirsh/reticulate-splines', True)
container.logs() spline 1...\\nReticulating spline 2...\\n'
```

**Comment by vfdev-5** [comment]
detach or not detach this is the question :)
Well, actually, the context is that I do not understand why there is no cv2 module in msdp-apex-vision image and I can not rerpo that locally...

**Comment by trsvchn** [comment]
cv or not 2cv ... or cv2

**Comment by trsvchn** [comment]
It seems to work fine

**Comment by vfdev-5** [comment]
Let's see if we can finally update our docker images

**Pull request merged**
