### PR TITLE
Changed gitignore for full python

### PR DESCRIPTION
**Pull request by AntoinePrv**
I added the full python gitignore to avoid having unnecessary files pop up in git.
Added the previous files from gitignore to this one.

### CODE REVIEW

**Comment by vfdev-5** [comment]
@AntoinePrv we discussed that point previously and yes that make sense to add things like coverage dist build etc. btw for things specific to your environment you can add them to your local gitignore.

**Comment by AntoinePrv** [comment]
@vfdev-5 ok, sorry for the double.

I noticed the `.pytest_cache` generated running the test in Python2 (`python2 -m pytest`)

**Comment by vfdev-5** [comment]
Antoine, no problems. Could you please add to ignore the distribution part : 
```
# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST
```
and the testing part 
```
# Unit test / coverage reports
htmlcov/
.tox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
.hypothesis/
.pytest_cache/
```

**Comment by vfdev-5** [comment]
LGTM! @alykhantejani if you are OK with this modifications, please merge it.

**Comment by alykhantejani** [comment]
Thanks @AntoinePrv!

**Pull request merged**
