### PR TITLE
Improve FB metric for DDP

### PR DESCRIPTION
**Pull request by KickItLikeShika**
Improving `FractionalBias` implementation to be compatible with DDP and add the necessary tests

Check list:

- [x] New tests are added (if a new feature is added)
- [x] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by KickItLikeShika** [comment]
Regarding the TPU test failure https://github.com/pytorch/ignite/pull/1805/checks?check_run_id=2122146650, i guess we got the same issue in #1699, i will try to fix it the same way

**Comment by vfdev-5** [comment]
@KickItLikeShika thanks ! yes, I think it should be division by zero somewhere...

**Comment by KickItLikeShika** [comment]
@vfdev-5 can you please check this https://github.com/pytorch/ignite/pull/1805/checks?check_run_id=2122812029

**Comment by KickItLikeShika** [comment]
@vfdev-5 You mean by reducing the tolerence is should be smaller than 1e-15, right? It should be for example 1e-30

**Comment by vfdev-5** [comment]
I mean pytest.approx tolerence, like here: https://github.com/pytorch/ignite/blob/f76c392725f320e0f5be3b94f4b06155f29f2460/tests/ignite/metrics/test_root_mean_squared_error.py#L132

**Comment by KickItLikeShika** [comment]
@vfdev-5 i have tried to manipulate the tolerence or the eps but it didn't work, still getting the same error

**Comment by vfdev-5** [comment]
@KickItLikeShika let's try to repro the issue locally. Please, follow these installation steps:
https://github.com/pytorch/ignite/blob/b973213e2d1d5024991401e369ad1a01b5092af9/.github/workflows/tpu-tests.yml#L52-L65

and run the test:
https://github.com/pytorch/ignite/blob/b973213e2d1d5024991401e369ad1a01b5092af9/.github/workflows/tpu-tests.yml#L67-L74
or even
```bash
pytest tests/ignite/contrib/metrics/regression/test_fractional_bias.py::test_distrib_single_device_xla -vvv -m tpu
```

**Comment by KickItLikeShika** [comment]
@vfdev-5 it work now, Thanks!

**Review by sdesrozis — APPROVED** [review]
@KickItLikeShika Thank you for this work! LGTM

**Comment by sdesrozis** [comment]
Horovod is ko 😔

**Comment by KickItLikeShika** [comment]
@sdesrozis yes i see! but i think it's not related, right? as the tests for `FractionBias` have been passed

**Comment by KickItLikeShika** [comment]
@sdesrozis please restart the CI to see what's going to happen..

**Comment by sdesrozis** [comment]
Let’s see tomorrow about this failure @vfdev-5

**Comment by KickItLikeShika** [comment]
@sdesrozis it works fine, thanks!

**Comment by vfdev-5** [comment]
@KickItLikeShika probably we have to adjust tolerance for GPU tests as well : https://app.circleci.com/pipelines/github/pytorch/ignite/1607/workflows/381ab87c-6226-466e-ab64-4bbe8a835f56/jobs/4649

**Pull request merged**
