### PR TITLE
[ci] migrate stable binaries release to github actions

### PR DESCRIPTION
**Pull request by ydcjeff**
Part of #1442 

Description: migrate binaries release to github actions

Check list:
* [ ] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by ydcjeff** [comment]
@vfdev-5 can this workflow works with release? or do we need to provide `tags`?

**Comment by vfdev-5** [comment]
@ydcjeff thanks for the PR ! Migrating binary releases is very important and should be carefully done and tested. Just few remarks, I already provided a script for conda here: https://github.com/pytorch/ignite/blob/master/conda.recipe/build_and_upload.sh
and for conda and pypi it should done the same as here : https://github.com/pytorch/ignite/blob/master/.github/workflows/binaries-nightly-release.yml

**Comment by ydcjeff** [comment]
@vfdev-5 okay now?

**Comment by ydcjeff** [comment]
@vfdev-5 ready to review!

**Review by vfdev-5 — APPROVED** [review]
Looks good. Let me check everything on my fork before merging to the master

**Comment by ydcjeff** [comment]
@vfdev-5 any chance we can merge this?

**Comment by vfdev-5** [comment]
@ydcjeff yes, it will be merged once I have tested it on my fork by creating a tag and launching release process. Unfortunately, I hadn't yet time to work on that.

**Comment by vfdev-5** [comment]
Checked here: https://github.com/vfdev-5/ignite/actions?query=workflow%3A%22Stable+Releases%22

**Pull request merged**
