### PR TITLE
Removes deprecated CustomPeriodicEvent

### PR DESCRIPTION
**Pull request by Tawishi**
In response to https://github.com/pytorch/ignite/issues/1247#issuecomment-683140646 

_Description_: Removes the missed out instance of  ```CustomPeriodicEvent``` from notebook example:
https://github.com/pytorch/ignite/blob/master/examples/notebooks/EfficientNet_Cifar100_finetuning.ipynb

### CODE REVIEW

**Comment by vfdev-5** [comment]
@Tawishi thanks for the PR, however here we have to replace ` CustomPeriodicEvent` by the new API as I described it here : https://github.com/pytorch/ignite/issues/1247#issuecomment-682166335

Please, update the PR according to that and if you could rerun it inside [Colab](https://colab.research.google.com/github/pytorch/ignite/blob/master/examples/notebooks/EfficientNet_Cifar100_finetuning.ipynb) it would be awesome.
Let me know if you have any questions.

**Comment by Tawishi** [comment]
@vfdev-5 I am facing this error and a warning while installations. Please help.

I ran the second command and got this in the terminal window.
```
1. git clone https://github.com/NVIDIA/apex && cd apex
2. pip install --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
```
Screenshot from 2020-09-01 12-39-33

It seems to a Python3.3 error as stated in this [post](https://stackoverflow.com/questions/15036594/python-3-3-typeerror-unsupported-operand-types-for-nonetype-and-str). How to go about this?

**Comment by vfdev-5** [comment]
@Tawishi I think it could not identify the location of cuda library. And also there is a message saying that there is no GPUs on the system... May I ask you what would you like to do ?

If you would like to test your modifications, I'd suggest you to use Colab where you can choose a system with GPU and cuda properly installed.

**Comment by Tawishi** [comment]
I will try out Colab and let you know if I face any problem.

**Comment by Tawishi** [comment]
I will try out Colab and let you know if I face any problem.

**Comment by vfdev-5** [comment]
@Tawishi do you need any help with the PR ?

**Comment by Tawishi** [comment]
> @Tawishi do you need any help with the PR ? Feel free to reach me out at discord if you need to ask several questions...

Apologize for the delay. 
Please send me your username and tag. I am still working on the PR.

**Comment by vfdev-5** [comment]
Here it is vfdev-5#4458 at https://discord.com/channels/720788516837261322/

**Comment by vfdev-5** [comment]
Closed in favor of https://github.com/pytorch/ignite/pull/1389

**Pull request closed without merging**
