### PR TITLE
fix an error message of confusion_matrix.IoU

### PR DESCRIPTION
**Pull request by BowmanChow**
Description:

An error message in ignite.metrics.confusion_matrix.IoU is confusing and does not match the condition check, which might lead to misunderstanding. I update the error message to make it match the  condition check.

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@BowmanChow thanks for the PR, I let @sadra-barikbin review it and comment out

**Review by sadra-barikbin — CHANGES_REQUESTED** [review]
Hi, thanks for the PR. Could you please apply this change to other places of confusion_matrix.py? For example line 396.

**Comment by BowmanChow** [comment]
Hi @sadra-barikbin , I made another change and force-pushed, because I want to keep the commit tree clean. I'm not sure whether force-push is ok. Is it mergable?

**Comment by vfdev-5** [comment]
@BowmanChow yes, it is ok to push-force. As it is your first contribution we need to approve to run the CI

**Comment by BowmanChow** [comment]
@vfdev-5 I'm sorry that I thought my changes were so small and don't need a check. I will have the formatting and test run.

**Comment by BowmanChow** [comment]
Hi @vfdev-5 , I've completed the formatting and test_confusion_matrix.py check.

**Review by vfdev-5 — APPROVED** [review]
Thanks for the PR @BowmanChow ! LGTM
CI failures are unrelated. I'll merge your PR once we fixed issues on master and I updated your PR.

**Pull request merged**
