### PR TITLE
Replace relative paths with raw.githubusercontent

### LINKED ISSUE #1626: Images not rendered on PyPI
## 📚 Documentation
The logo and other assets on the project README.md are not rendered on the PyPI page of [pytorch-ignite](https://pypi.org/project/pytorch-ignite/)
This is because PyPI does not read the repo for the images, and we'll have to use external links for the image. (reference [here](https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github))
We could use the `https://raw.githubusercontent.com/*`  counterparts for the assets instead of specifying the path

By specifying the path, I mean the following
https://github.com/pytorch/ignite/blob/6753b19b74fd8d128188dd0a75b405d19aa515b5/README.md#L5

Just a suggestion, please ignore if it is unnecessary :)

### PR DESCRIPTION
**Pull request by Devanshu24**
Fixes #1626 

Description:
Replaced all the instances with `src="assets/*"` to the corresponding `raw.githubusercontent.com` URLs

Not as I elegant as expected, but I think this should work. Any suggestions?
Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@Devanshu24 looks good! Could you please make a test release from your fork on test-pypi (https://test.pypi.org/) with twine to check if it works ?

Something like that:
```
python setup.py sdist bdist_wheel
twine upload --repository-url https://test.pypi.org/legacy/ dist/*
```

**Comment by Devanshu24** [comment]
Sure, I'll get to it! :)

**Comment by Devanshu24** [comment]
Uploaded the package, looks beautiful! [PyPI link](https://test.pypi.org/project/pytorch-ignite-demo/0.5.0/)

Once you are done seeing it, I will delete the package :)

**Comment by vfdev-5** [comment]
Looks awesome, thanks @Devanshu24 !

**Pull request merged**
