### PR TITLE
Add declarative trainer

### PR DESCRIPTION
**Pull request by Minyus**
Fixes # 912

Description:
Higher API for training will improve usability of Ignite.

Check list:
* [ ] New tests are added (if a new feature is added)
* [x ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by sdesrozis** [comment]
@Minyus Thank you very much for this PR !!

I make you my feedback on your proposal quickly :)

**Comment by vfdev-5** [comment]
@Minyus thanks a lot for the PR ! I really appreciate your contribution, however it would be great to discuss more about the API. We already stated some general remarks on the API in the related issue #912 

In my opinion, class `NetworkTrain` has very specific integrations with MLflow which can be a limitation for some users. Another point is about exposing trainer in the higher API in case of adding more user-specific handlers. 

please, let's discuss more about the API in #912.

**Comment by vfdev-5** [comment]
@Minyus can we work out this at first ? 
```python
class TimeLimit:
    def __init__(self, limit_sec=3600):
        self.limit_sec = limit_sec
        self.start_time = time.time()

    def __call__(self, engine):
        elapsed_time = time.time() - self.start_time
        if elapsed_time > self.limit_sec:
            log.warning("Reached the time limit: {} sec. Stop training".format(self.limit_sec))
            engine.terminate()
```

This looks good enough. Maybe, in addition, we can set `Checkpoint` or `ModelCheckpoint` to save the work before terminating ?

**Comment by Minyus** [comment]
@vfdev-5 
OK, I'll move `TimeLimit` to `ignite/handlers/time_limit.py`. 
Let's add saving before terminating to ToDo list as it needs further consideration (e.g. what if model checkpoint path is not specified, etc.)

**Comment by vfdev-5** [comment]
@Minyus 

> @vfdev-5
> OK, I'll move `TimeLimit` to `ignite/handlers/time_limit.py`.
> Let's add saving before terminating to ToDo list as it needs further consideration (e.g. what if model checkpoint path is not specified, etc.)

@Minyus thanks, but it would be much better to split this PR into several ones. One PR by feature.
So, please, send the code of `TimeLimit` into a new PR. It would be nice to follow  https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md 
Thanks

**Comment by Minyus** [comment]
As discussed in Slack, this PR is suspended.

Meanwhile, please feel free to send PR (including adding documentation, test, example, etc.) to PipelineX so that I can send a complete PR to Ignite later on.

higher API for training
https://github.com/Minyus/pipelinex/blob/master/src/pipelinex/ops/ignite/declaratives/declarative_trainer.py

MNIST example to use higher API
https://github.com/Minyus/pipelinex/blob/master/examples/mnist/mnist_with_declarative_trainer.py

TimeLimit handler
https://github.com/Minyus/pipelinex/blob/master/src/pipelinex/ops/ignite/handlers/time_limit.py

Cohen Kappa Score metric
https://github.com/Minyus/pipelinex/blob/master/src/pipelinex/ops/ignite/metrics/cohen_kappa_score.py

Please also feel free to copy any code in PipelineX to use in PyTorch Ignite.
I'm happy to see Ignite to be enhanced in any way.

**Comment by sdesrozis** [comment]
Thank you again and see you soon !!

**Pull request closed without merging**
