### PR TITLE
Add mocked  supervised evaluator test

### LINKED ISSUE #1751: Improve the supervised evaluator and trainer tests by using mocking
## 🚀 Feature

As it became clear in this PR: 1714. Some of the functionalities of both the supervised evaluator and trainer are not tested as we need to mock some of the underlying functions i.e. evaluate steps or engines.

I suggest mocking those objects and write test cases that test that those mocks were called in different evaluation scenarios. We already use mocks in some of our tests and we can start unify them across all tests that include complex execution scenarios.

### PR DESCRIPTION
**Pull request by Moh-Yakoub**
Fixes #1751

Description:

In a previous PR #1714. we weren't able to test the full functionality due to the fact that we weren't mocking the evaluator and didn't interrupt them before execution.

I've added a mocked version of the evaluator tests to be able to test that we are using the correct evaluation steo

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Review by vfdev-5 — APPROVED** [review]
LGTM, thanks @Moh-Yakoub !

**Comment by vfdev-5** [comment]
@ydcjeff would you like to review ?

**Review by ydcjeff — APPROVED** [review]
LGTM

**Comment by vfdev-5** [comment]
@Moh-Yakoub unfortunately, GPU tests are now broken due to this PR : 
https://app.circleci.com/pipelines/github/pytorch/ignite/1574/workflows/4d2f11dd-70c4-4c1d-81c2-3be050b45365
- test_create_supervised_evaluator_on_cuda_with_model_on_cpu

Could you please provide a fix ?

**Pull request merged**
