### PR TITLE
[Step 2/4: Ready for review] Allow attaching metric to engine multiple times

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Depends on https://github.com/pytorch/ignite/pull/325
See also: https://github.com/pytorch/ignite/pull/323#issuecomment-436815481

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
Why the CI build is canceled?

**Comment by vfdev-5** [comment]
> Why the CI build is canceled?

This must be a bug in travis. I just restarted previously failed test job on py35

**Comment by vfdev-5** [comment]
@jasonkriss please review and merge if OK

**Comment by jasonkriss** [comment]
Looks good! Thanks @zasdfgbnm!

**Comment by vfdev-5** [comment]
@zasdfgbnm sorry for revealing this one. I'm just wondering in which case actually user would like to add the same handler to the same event multiple times ?

**Comment by zasdfgbnm** [comment]
@vfdev-5  `add_event_handler` has `args` and `kwargs` which would be passed to handler function. The user might create handlers with same function, but different arguments. Such as:

```python
def write_result_to_file(engine, index):
    result = engine.state.xxx[index]
    result = .....  # do some computation
    open('result-{}.txt'.format(index), 'w').write(result)

trainer.add_event_handler(write_result_to_file, 'result1')
trainer.add_event_handler(write_result_to_file, 'result2')
trainer.add_event_handler(write_result_to_file, 'result3')
```

**Comment by vfdev-5** [comment]
@zasdfgbnm Okay, this can make sense. Let's leave as is.

**Pull request merged**
