### PR TITLE
refactor: remove redundant line as .reset() is call in Metrics().__init()

### PR DESCRIPTION
**Pull request by MarcBresson**
The same line was in reset() and init() which is unecessary.

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Review by vfdev-5 — APPROVED** [review]
LGTM, if mypy check wont complain

**Comment by MarcBresson** [comment]
Do we even know why the kernel is created in the reset method ?

I think I removed it on the wrong line. It should only be called in init().

**Comment by vfdev-5** [comment]
Yes, you are right, we do not need to recreate the kernel on reset.

**Review by vfdev-5 — APPROVED** [review]
LGTM, thanks for the fix @MarcBresson !

**Pull request merged**
