### PR TITLE
Stores training checkpoints and best model as archived files

### PR DESCRIPTION
**Pull request by vfdev-5**
Description:
Idea is to reduce storage space by default, when using `setup_common_training_handlers` and `save_best_model_by_val_score` methods from `ignite.contrib.engines.common`.

Check list:
* [x] New tests are added (if a new feature is added)
* [x] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

cc @justusschock @ykumards

### CODE REVIEW

**Comment by ykumards** [comment]
Hi @vfdev-5, just a quick question: is there any downside to saving the models as archived `.pth` files? If no, am wondering why this argument is set to false by default in `ModelCheckpoint`?

**Comment by vfdev-5** [comment]
@ykumards it is mainly for somewhat "compatilibity" reasons that `archived=False`. Previously we saved everything as `.pth`, even there is no code to change, user can be surprised by seeing now `.pth.tar` instead, I think.

**Comment by justusschock** [comment]
I think this is good for default settings.

Just a side note: We should maybe change the extension in general from `.pth` to `.pt` since `.pth` is also the extension used internally in python for [package configurations](https://docs.python.org/3.6/library/site.html). But probably this should be done in a separate PR (just a reminder).

**Comment by vfdev-5** [comment]
> We should maybe change the extension in general from .pth to .pt since .pth is also the extension used internally in python for package configurations.

@justusschock yes, you are right! Let's create another PR and merge it for 0.4.0, not 0.3.X

> I think this is good for default settings.

`.pth` or `.pth.tar` ?

**Comment by justusschock** [comment]
Sorry that it was not clear. I would prefer `.pth.tar` because we should aim for an obvious difference for different file types.

**Comment by vfdev-5** [comment]
Checked with recent pytorch and it seems like it is useless to add `.tar` in the end of the file as it is not archived.
```python
import torch
from torchvision.models.resnet import resnet152
m = resnet152()
torch.save(m.state_dict(), "m.pt")
torch.save(m.state_dict(), "m.pth.tar")
torch.save(m.state_dict(), "m.pt.tar")
!ls -allh m.*
> 231M Mar 15 21:35 m.pt
> 231M Mar 15 21:35 m.pt.tar
> 231M Mar 15 21:35 m.pth.tar
```

**Comment by justusschock** [comment]
That's true, but we could manually create an archive (with `tarfile` or `zipfile` or something similar)

**Comment by vfdev-5** [comment]
> That's true, but we could manually create an archive (with tarfile or zipfile or something similar)

Well, loading such checkpoint wont be evident for users, I think.

I close the PR.

**Comment by justusschock** [comment]
Starting with PyTorch 1.4 there is a new argument for that in `torch.save`: `_use_new_zipfile_serialization=False`. We could probably check for the Pytorch version and use this argument, when the version is recent enough, I guess. 
Although, this argument is not yet part of the official docs.

**Comment by vfdev-5** [comment]
@justusschock yes, I saw this argument too, I checked with True/False but output size is still the same.

**Comment by justusschock** [comment]
This is strange, since I had a look at the source code and it seems they are actually writing it to a zip file. But I don't know, how well you can compress a binary dump as it comes from pickle...

**Pull request closed without merging**
