### PR TITLE
Fix MyPy issue

### PR DESCRIPTION
**Pull request by sadra-barikbin**
Description:
Using new MyPy release(0.991) raises some errors. This PR attempts to resolve them.

### CODE REVIEW

**Comment by sadra-barikbin** [comment]
@vfdev-5 , in `ignite.handlers.base_logger.BaseHandler` and its children why is `Union[str, Events]` is being used as type annotation for the second argument in `__call__` method and not `Union[str, EventEnum]`?

**Comment by vfdev-5** [comment]
Events type is a bit tricky and we need unify the typehints at some point. As a rule of thumb, we have 
- EventEnum = base class for events: built-in and custom
- Events = built-in event for the Engine
- EventsList = list of events
- str = string as event
 
Let's first fix mypy issues and in a follow-up PR we can tackle typehint for events.

**Review by vfdev-5 — APPROVED** [review]
LGTM, thanks @sadra-barikbin !

**Comment by vfdev-5** [comment]
As failing tests are unrelated, merging this PR

**Pull request merged**
