### PR TITLE
Fix `distutils` deprecation warning

### LINKED ISSUE #2472: Fix DeprecationWarning: distutils Version classes are deprecated
We need to fix `DeprecationWarning: distutils`:

```
  /home/docker/actions-runner/_work/ignite/ignite/tests/ignite/engine/test_create_supervised.py:587: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    @pytest.mark.skipif(LooseVersion(torch.__version__) < LooseVersion("1.6.0"), reason="Skip if < 1.6.0")
```
- In the CI and in the code

In addition to the code change we have to figure out if we need to add `packaging` as a dependency.
It is most probably brought with some other packages but we have to ensure that on a clean environment it is (or not) installed together with for example pytorch.

---

`packaging` is not installed with torch cpu on Ubuntu, checked ubuntu:latest docker container.
```
apt-get install -y python3 python3-pip
python3 --version
Python 3.8.10

pip3 install torch -f https://download.pytorch.org/whl/cpu/torch_stable.html
pip3 list | grep torch
torch             1.10.2+cp

python3 -c "import packaging"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'packaging'
```

### PR DESCRIPTION
**Pull request by DevPranjal**
Fixes #2472 

Description: Fix `distutils` deprecation warning by using `Version` from `packaging.versioning` in place of `LooseVersion`

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@DevPranjal thanks for the PR, looks good. Do you think the failure is related to the change ?

**Comment by vfdev-5** [comment]
@DevPranjal they are unrelated, provided a temporary CI fix: https://github.com/pytorch/ignite/pull/2477

**Review by vfdev-5 — APPROVED** [review]
LGTM, thanks @DevPranjal

**Comment by DevPranjal** [comment]
Tests related to `pytorch-nightly` are passing since `AttributeError: module 'distutils' has no attribute 'version'` has been [fixed](https://github.com/pytorch/pytorch/pull/69904) recently. 
This also seems related to this PR, since `distutils` is involved. Will look into it.

**Comment by vfdev-5** [comment]
@DevPranjal let's temporarily fix distutils to an older version such that stable pytorch will pass as well ?

**Comment by vfdev-5** [comment]
@DevPranjal can you also please replace this: 
- https://github.com/pytorch/ignite/blob/6d385eb903b83f048d67c7a07df4dae214437e30/tests/ignite/handlers/test_checkpoint.py#L11

**Comment by DevPranjal** [comment]
@vfdev-5 all checks passing now :)

**Review by vfdev-5 — APPROVED** [review]

**Pull request merged**
