### PR TITLE
GH Action for docker builds

### PR DESCRIPTION
**Pull request by trsvchn**
Related to #1644 and #1721

Description:

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by trsvchn** [comment]
I think I finally got it how to trigger how bind particular step with certain dir update.

**Comment by trsvchn** [comment]
Nope)

**Comment by vfdev-5** [comment]
Thanks for testing that, @trsvchn !
I also wonder if we couldn't solve permission issue of trigger build job using pull request target trick ?

**Comment by trsvchn** [comment]
@vfdev-5 probably, but can verify it only after the merge, like we did for code-style

**Comment by vfdev-5** [comment]
> @vfdev-5 probably, but we can verify it only after the merge, like we did for code-style

Sounds good! Let's do it like for code-style. Just to make sure, the permission issue there is related to probably skipped `CIRCLE_TOKEN` as it is on fork.

**Comment by vfdev-5** [comment]
I see that you are trying to find out if trigger next stops or not depending on modified. I did something like that here : https://github.com/pytorch/ignite/blob/master/.circleci/trigger_if_modified.sh . May help...

**Comment by trsvchn** [comment]
> > @vfdev-5 probably, but we can verify it only after the merge, like we did for code-style
> 
> Sounds good! Let's do it like for code-style. Just to make sure, the permission issue there is related to probably skipped `CIRCLE_TOKEN` as it is on fork.

it's hard to say, we need to try. I don't know how user defined tokens interact with `pt_target`

**Comment by trsvchn** [comment]
@vfdev-5 
Yeah I think the main part here is https://github.com/pytorch/ignite/blob/007d320150fa915d7ac8757ddb586aaa9c427682/.circleci/trigger_if_modified.sh#L41

I've already tried:

`git diff-tree --no-commit-id --name-only -r HEAD`

and 

`git diff --name-only HEAD^ HEAD`

But it didn't help

I think it's because of checkout action and detached head checkout by default

**Comment by trsvchn** [comment]
going to try prepared solutions)
https://github.com/futuratrepadeira/changed-files

**Comment by trsvchn** [comment]
wow that actions works!
https://github.com/pytorch/ignite/pull/1724/checks?check_run_id=2007661996#step:6:7

**Comment by trsvchn** [comment]
going to update some docker

**Comment by trsvchn** [comment]
Oh, yeah it works!

**Comment by trsvchn** [comment]
Interesting fact: `changed-files` action works only with PRs events

**Comment by vfdev-5** [comment]
Great! Currently, the problem will be with GA that wont be able to build our large HVD images...
I think we can reuse that with more finegrained trigger circle ci ...


> Interesting fact: changed-files action works only with PRs events
Yeah, that's what they say "GitHub action to export a PR's changed files"

**Comment by trsvchn** [comment]
@vfdev-5 so we are going to try to trigger Circle CI  through `pull_request_target` events, right?

**Comment by trsvchn** [comment]
yes, definitely, we have to try parallel build

**Comment by trsvchn** [comment]
Going to try smth like this

```yml
jobs:
  prepare:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Changed Files Exporter
        id: files
        uses: futuratrepadeira/changed-files@v3.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # Get list of modified files
      - run: echo "modified=${{ steps.files.outputs.files_created }} ${{ steps.files.outputs.files_updated }}" >> $GITHUB_ENV

  build-hvd:
    # Trigger only if folder is modified
    if: contains(env.modified, 'hvd')
    name: Build all Horovod flavoured PyTorch-Ignite images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavour: [ "hvd-base", "hvd-vision", "hvd-nlp" ]
    steps:
      - run: |
        pip install PyYAML
        export PTH_VERSION=`python -c "import yaml; f=open('.circleci/config.yml'); d=yaml.safe_load(f); print(d['parameters']['build_docker_image_pytorch_version']['default'])"`
        export HVD_VERSION=`python -c "import yaml; f=open('.circleci/config.yml'); d=yaml.safe_load(f); print(d['parameters']['build_docker_image_hvd_version']['default'])"`
        cd docker
        bash build.sh hvd ${{ matrix.flavour }}
        bash build.sh hvd ${{ matrix.flavour }}
        bash build.sh hvd ${{ matrix.flavour }}
```

**Comment by trsvchn** [comment]
Huh, no triggering now

**Comment by vfdev-5** [comment]
Screen Shot 2021-03-01 at 23 08 29

I was thinking that matrix should be declared on jobs level or even higher... like here  : https://github.com/pytorch/ignite/blob/007d320150fa915d7ac8757ddb586aaa9c427682/.github/workflows/unit-tests.yml#L24

**Comment by trsvchn** [comment]
not so easy, as always)

**Comment by trsvchn** [comment]
@vfdev-5 Just look at this!

Screenshot from 2021-03-02 03-37-21

**Comment by trsvchn** [comment]
oh, no! Looks like it still treats msdp as modified. 

Screenshot from 2021-03-02 04-00-17

**Comment by trsvchn** [comment]
I have an idea, github runner, a virtual machine, that runs a job, already ships with docker images:

Screenshot from 2021-03-02 04-59-10

I'm planning to remove them before our build

**Comment by trsvchn** [comment]
Haha))

Screenshot from 2021-03-02 05-41-56

**Comment by vfdev-5** [comment]
Wow, what a great progress on that ! Thanks a lot @trsvchn !!

**Comment by vfdev-5** [comment]
Now, let's do the following to merge this PR : 
- remove pull_request option from "Trigger Build And Publish Docker Images", such that we do not have a failing action.
- revert back modifications that trigger images rebuild.
- rename "docker-build-temporary.yml" -> "docker-build.yml"

And in a follow-up PR let's add a python script that could test built images as discussed in the issue.

**Review by vfdev-5 — APPROVED** [review]
Thanks a lot @trsvchn !

**Comment by vfdev-5** [comment]
@trsvchn oh, I just realized that we are not doing correct here now:
we have to build in sequence the images: 
- `base` -> [vision, nlp]
- `hvd-base` -> [hvd-vision, hvd-nlp]
- `hvd-apex` -> [hvd-apex-vision, hvd-apex-nlp]
- ...

Otherwise, buildling for example `nlp`, it fetchs another `base` image...

**Comment by trsvchn** [comment]
@vfdev-5 Oh, because of multi-stage builds, I have never tried it btw, 

so `nlp` and `vision` need `base`, right? they should have access to that built image, right?

**Comment by vfdev-5** [comment]
Well, actually, it is not because of mutli-stage but just, for example, nlp image uses `FROM base:latest`.
We can simply try to squash parallel builds of [base, vision, nlp] and related into a sequential and run
- base
- hvd-base
- hvd-apex
- msdp-apex
in parallel

**Comment by trsvchn** [comment]
Or, we can try smth like:

```yml
jobs:
  build-base:
    # build base
    # upload image as artifact

  build-vision
    needs: build-base
    # download image as artifact
    # build vision
...
```

**Comment by trsvchn** [comment]
Because I'm not sure about space

**Comment by vfdev-5** [comment]
Instead of uploading temp images, we can try if steps could reuse the same docker env between...

Yes, space question can be blocking ...

**Comment by trsvchn** [comment]
> As different jobs use different runners, so we can’t pass docker image between jobs.

> Is it possible to share dockerfile between job1 and job4 in your scenario, and then build it in job4 again to generate docker image instead of pulling it from docker hub?  

> You can use the upload-artifact and download-artifact actions to share data between jobs in a workflow.

> https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts#passing-data-between-jobs-in-a-workflow 99

**Comment by trsvchn** [comment]
I also found this https://github.community/t/whats-the-recommended-way-to-pass-a-docker-image-to-the-next-job-in-a-workflow/17225/4

> Github provided Github Package Registry which could hold your docker image like docker hub registry. If you are using public repo, it is free. But there are some limits for private repo.

**Comment by trsvchn** [comment]
We can use Package Registr to store our docker images

**Comment by vfdev-5** [comment]
I think we can pass docker env between steps in a single job, right ? Otherwise, yes, we can use GH Package registry.

```
jobs:
   build-hvd
   steps:
      - build-hvd-base
      ....
      - build-hvd-nlp
      ....
      - build-hvd-vision
```

**Comment by trsvchn** [comment]
Yep, exactly! especially in hvd case

**Comment by vfdev-5** [comment]
OK, let's try either : 
1) upload-artifact and download-artifact 
2) GH registry and clean up after the builds

**Comment by trsvchn** [comment]
+ there is delete-artifact
we can use it to cleanup, since I am not sure what will happen if we try to upload twice or smth

**Comment by trsvchn** [comment]
I am going to try this artifact experiment in my repo, to avoid massive artifact mess up here :)

**Comment by vfdev-5** [comment]
Sounds great! Thanks @trsvchn !

**Comment by trsvchn** [comment]
Well, I've configured artifacts exchange between jobs, and it works fine for small images.

The problem is in the lack of space when making a tar archive for image, I'm talking about:

```bash
docker save -o image.tar image:latest
```

but we get:

```bash
Error response from daemon: write /var/lib/docker/tmp/docker-export-437653913/54625702f120aa44ba56fed9756f8b1018f55dfc22efffbf2a6064070de5e490/layer.tar: no space left on device
```

I've inspected GH Actions runner space. This is default filesystem on start (before docker build):

```
Filesystem      Size  Used Avail
total           109G   69G   39G
```

I'm thinking to remove some packages to free up space for docker save. 

@vfdev-5 @ydcjeff @sdesrozis What heavy packages can we remove w/o effect on docker?

**Comment by vfdev-5** [comment]
@trsvchn thanks for the update !
How about removing pytorch/pytorch:*-devel image before creating the archive ? This should save about 10Gb maybe.

**Comment by trsvchn** [comment]
@vfdev-5 Yes, I was thinking about it, but can we remove it? I've tried locally and got this

```bash
Error response from daemon: conflict: unable to delete 7554ac65eba5 (cannot be forced) - image has dependent child images
```

**Comment by vfdev-5** [comment]
Yes, true, we can not remove it for msdp images, but should work for hvd.

**Comment by trsvchn** [comment]
https://github.com/actions/virtual-environments/issues/709#issuecomment-612569242

**Comment by vfdev-5** [comment]
We can try that as well

**Comment by sdesrozis** [comment]
@trsvchn @vfdev-5 

Regarding the packages below
```
228.3M google-chrome-stable
 211.8M firefox
 208.5M dotnet-sdk-5.0
 193.6M llvm-10-dev
 189.5M llvm-9-dev
 185.0M dotnet-sdk-3.1
 170.2M powershell
 163.1M llvm-8-dev
 118.9M mysql-server-core-8.0
 109.5M mono-devel
  81.0M podman
  79.3M libllvm11
  78.7M mongodb-org-server
  70.3M libllvm10
```
do we need 
* `firefox` and `google-chrome` ?
* `dotnet` ?
* db servers like `mongodb` and `sqll` ?
* `podman` ?
* multiple `llvm` ?

Sorry if this is not relevant according to the current thread ....

**Comment by trsvchn** [comment]
@sdesrozis Thanks for suggestions! But idea save/load docker image is not working, now we are building all 3 images in a one job and

using
```bash
sudo rm -rf "/usr/local/share/boost"
sudo rm -rf "$AGENT_TOOLSDIRECTORY"
```
freed enough space for that purpose

**Comment by harshit2000** [comment]
Hi, is this issue still not resolved. If not, can I get the issue note on the last updated work?

**Comment by harshit2000** [comment]
@vfdev-5  Sure, thanks for the info

**Pull request merged**
