### PR TITLE
Format small

### LINKED ISSUE #1496: Replace string .format with f-string
## 🚀 Feature

Once #1495 is merged we can replace all `.format` with f-strings.

If interested in helping with the issue, please comment here and send a PR according to our contributing guide.
Feel free to ask questions for details if needed.

### PR DESCRIPTION
**Pull request by uribgp**
Fixes  (partial fix for f-string reformatting)

Related to #1496

Description: Breaking up large pull

Check list:
* [ ] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Review by vfdev-5 — APPROVED** [review]
Thanks @uribgp !

**Comment by vfdev-5** [comment]
As you put `Fixes #1496` in the description. If I merge this PR it will close related issue. This PR is the last chunk or it still remains more files to update ?

**Comment by uribgp** [comment]
> As you put `Fixes #1496` in the description. If I merge this PR it will close related issue. This PR is the last chunk or it still remains more files to update ?

Edited that out.  There's still a lot of files remaining.

**Comment by vfdev-5** [comment]
> > As you put `Fixes #1496` in the description. If I merge this PR it will close related issue. This PR is the last chunk or it still remains more files to update ?
> 
> Edited that out. There's still a lot of files remaining.

OK, I see. Just put the next time `Related to #1496`.

**Pull request merged**
