### PR TITLE
updated events,py  updated function  once_event_filter and  before_an…

### PR DESCRIPTION
**Pull request by uniyalmani**
…d_after_event_filter issue #2853

for before_and_after_event_filter used arithmetic progression  and once_event_filter issue #2853

Fixes #{issue number} #2853

Description: updated two function once_event_filter, before_and_after_event_filter.

### CODE REVIEW

**Comment by vfdev-5** [comment]
Please check this guide : https://github.com/firstcontributions/first-contributions on how to contribute efficiently. Thanks

**Comment by uniyalmani** [comment]
please consider latest one pull request i have added test cases in lastest one

**Comment by vfdev-5** [comment]
@uniyalmani I asked you previously to work with a single PR and not opening new ones. Please close all those PRs that wont be updated and shouldn't be considered.

**Comment by vfdev-5** [comment]
Closing this PR in favor of #2860 and #2858

**Pull request closed without merging**
