### PR TITLE
Adopt PyTorch's doc theme

### LINKED ISSUE #625: Switch website theme to PyTorch?
I am updating the docs theme to leverage [pytorch_sphinx_theme](https://github.com/pytorch/pytorch_sphinx_theme) so that Ignite docs look like PyTorch's. The diffs are minimal.

Pros:
- closer to PyTorch
- darkifiable with existing Userstyles (see screenshots)

Caveats:
- pytorch_sphinx_theme comes with footers that are not really relevant to Ignite, and I could not yet find a way to alter them.
- the links to various Ignite versions are eaten by some monster somewhere

Here are some screenshots (built with `make html` or with `sphinx-versioning ...`). What is your opinion? Should I open a PR?

## some text and code (that look nice IMO)

Screenshot 2019-09-14 at 20 00 54

Screenshot 2019-09-14 at 19 44 04

## the main caveat: PyTorch footer (irrelevant to Ignite)

Screenshot 2019-09-14 at 20 02 23

### PR DESCRIPTION
**Pull request by bosr**
Fixes #625 

Description:
As detailed in the issue, this is a proposal to switch the website's theme to PyTorch's. This illustrates Ecosystem membership and a cleaner theme. Additionally, existing Usercss plugins can darkify with almost no change.

I'm not sure yet that the versions links block will be properly styled when displayed on read-the-docs, but let's iterate over that.

Check list:
* [ ] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [X] Documentation is updated (if required)

### CODE REVIEW

**Comment by bosr** [comment]
A couple of remarks:
- The footer links to the rtd theme, but that comes from PyTorch's own footer, so I left it as is.
- From my understanding, `sphinx-versioning` builds the previous docs with there own doc tree, so they are missing the overriding `_templates/layout.html` that fix the header and footer for Ignite. As a consequence, those versions display PyTorch's header and footer.

**Comment by vfdev-5** [comment]
Thanks for the PR, @bosr ! Could you please deploy this solution at your fork gh-pages and we could see it at bosr.github.io/ignite ?

About overriding layout.HTML we can try to hack version build with manually installed layout ?

**Comment by bosr** [comment]
Just deployed to bosr.github.io/ignite

Caveats (my limitations, not the tools'):
- Regarding the layout.html override, I must say this is currently out of my league. 
- all versions do get built during the `sphinx-versioning push` process, but they crash because of the absence of sphinx-rtd-theme. This was not the case with `sphinx-versioning --use-master-conf build`. Here are the command lines I run

when building for preview and dev (from the `doc/pytorch-theme` branch):

    sphinx-versioning --use-master-conf build --greatest-tag --whitelist-branches master docs/source docs/build/html

when building for pushing (from the empty `gh-pages` branch):

    sphinx-versioning build -r feature_branch docs docs/_build/html

I think I need some help ;)

**Comment by bosr** [comment]
Ok, if I push from the `doc/pytorch-theme` branch using the following command, then all tagged branches get built (expected):

    sphinx-versioning --use-master-conf push --greatest-tag --whitelist-branches master docs/source gh-pages .

The updated version is live on my gh-pages.

**Comment by vfdev-5** [comment]
@bosr great progress on the PR ! I'll commit some changes in layout.html that makes it better.

Concerning the deployment and your points, we actually do no use `sphinx-versioning push` we just deploy what is built with travis ci : https://github.com/pytorch/ignite/blob/224076dabb7370d78be4b08294bcaec4f8880bc2/.travis.yml#L88-L112

In your deployed docs there is an issue we have to handle with versions once selected a version there is no more selector and footer appears. This should be probably related with layout.html ?

**Comment by bosr** [comment]
Hi, thanks @vfdev-5!

Regarding `layout.html`: as you probably have spotted, this file is just a modified copy of the original from pytorch_sphinx_theme package. I put it in `_templates` so that it overrides the original one. In the pytorch_sphinx_theme package, there is also a `versions.html` file (I don't override it) that is meant to be active when the docs are built for readthedocs.io. This template file is rendered at build time only if the `READTHEDOCS`env var exists during the build process. And I expected the current outstanding div element to be replaced by this rendered template.

I guessed (wrongly) that the Ignite docs where pushed on readthedocs, and thus you had a separate final process for handling that. Now, I understand that this readthedocs style for that menu comes from sphinx-versioning: in their docs [here](https://sphinxcontrib-versioning.readthedocs.io/en/latest/themes.html) they explain that they support a set of themes, which does not include pytorch_sphinx_theme.

So I guess this versions menu is a matter of css styling the current div element (no need to activate the `versions.html` template) and embed that styling in our `ignite-theme.css` to mimicks what is currently done.

Do you read this the same as me?

Ah ah, second time I pick an issue that reveals tricky ;)

**Comment by vfdev-5** [comment]
> Regarding layout.html: as you probably have spotted, this file is just a modified copy of the original from pytorch_sphinx_theme package. I put it in _templates so that it overrides the original one. 

Yes, I agree. However, it seems that when building with `sphinx-versioning` layout.html from _templates is not used...

> I guessed (wrongly) that the Ignite docs where pushed on readthedocs, and thus you had a separate final process for handling that. Now, I understand that this readthedocs style for that menu comes from sphinx-versioning: in their docs here they explain that they support a set of themes, which does not include pytorch_sphinx_theme.

Yes, they have their own [_template/versions.html](https://github.com/anmolsjoshi/sphinxcontrib-versioning/blob/master/sphinxcontrib/versioning/_templates/versions.html). Which is translated to a list if not sphinx_rtd_theme. Maybe we can update this...

> So I guess this versions menu is a matter of css styling the current div element (no need to activate the versions.html template) and embed that styling in our ignite-theme.css to mimicks what is currently done.

Well, maybe...

> Ah ah, second time I pick an issue that reveals tricky ;)

:)

**Comment by vfdev-5** [comment]
@bosr using updated : https://github.com/vfdev-5/sphinxcontrib-versioning

We can now use master's _templates in tags: 
```
 sphinx-versioning --use-master-conf --use-master-templates build --greatest-tag --whitelist-branches master docs/source docs/build/html
```
However, locally I can not manage to have master's css with ignite : ignite_theme.css

**Comment by bosr** [comment]
Thanks! On my side, to solve the unapplied `_template` css you mentioned, I'm trying to own the pytorch_sphinx_theme within the `docs/source/_theme` folder.

**Comment by bosr** [comment]
Hi, thanks to your update on sphinx-versioning, and after some super basic hacking in the end (took me some time to find it though), all version now build correctly and inherit the correct templates. This is live on my gh-pages.

Now remains the css styling of the versions.html div block, and we should be good to go.

**Comment by vfdev-5** [comment]
Now docs look awesome ! 
Just remarked that when you forced some of your push, you rewritten one of my commits : https://github.com/pytorch/ignite/pull/626/commits/c3adad77bab8b908d3e0ad85f4bd0f44e0c5a81b
could you please incorporate it ?

Just a nit on Ignite logo, can we make it a bit larger ?

> Now remains the css styling of the versions.html div block, and we should be good to go.

Any ideas how to do this ?

**Comment by bosr** [comment]
> Now docs look awesome !

PyTorch's theme and this community's content... Cool!

> Just remarked that when you forced some of your push, you rewritten one of my commits : [c3adad7](https://github.com/pytorch/ignite/commit/c3adad77bab8b908d3e0ad85f4bd0f44e0c5a81b)
> could you please incorporate it ?

Are you sure? I can still see that commit in my repo's history and I checked that all of its content is present in the actual files.

> Just a nit on Ignite logo, can we make it a bit larger ?

yup, done in the next push (along with .travis.yml update)

> > Now remains the css styling of the versions.html div block, and we should be good to go.
> 
> Any ideas how to do this ?

Yes, at least I can start with rtd's css for that div block, and adjust the fonts and colors.

**Comment by vfdev-5** [comment]
> Are you sure? I can still see that commit in my repo's history and I checked that all of its content is present in the actual files.

@bosr well, probably, my fault, sorry! yes I see it too, but didn't see the modifications on deployed site...

**Comment by vfdev-5** [comment]
For example, pytorch/text has also changed the theme but not the templates nor logo : 
https://pytorch.org/text/
Go Ignite ! :)

**Comment by bosr** [comment]
No problem! Can you check now? the latest push is visible

**Comment by bosr** [comment]
Of course the FAQ link does not work on v0.1.2 for instance, but I guess that's acceptable. Do you?

**Comment by vfdev-5** [comment]
> Of course the FAQ link does not work on v0.1.2 for instance, but I guess that's acceptable. Do you?

Yes, we can leave it like that...

@bosr as we update the docs, style etc I was also thinking to update the ignite's logo... 
1) keep pytorch's fire symbol but paint it in blue or something else
2) draw something else...
what do you think ?

**Comment by bosr** [comment]
Nice, I like the idea of keeping the PyTorch flame, or staying in the theme of the Ecosystem logos. Maybe updating the flame's color. For sure, I'd like the text font to be that of PyTorch, or very close. Let's sleep on that!

I working on the version block styling, but I might continue early morning tomorrow. Cheers!

**Comment by vfdev-5** [comment]
@bosr thanks for your help ! 

> For sure, I'd like the text font to be that of PyTorch, or very close.

At the moment of creation of the logo, I asked Soumith about PyTorch text font to make the same. He didn't know :) So, I picked Ubuntu font that IMO was close to PyTorch...

**Comment by bosr** [comment]
> @bosr thanks for your help !

My pleasure!

> > For sure, I'd like the text font to be that of PyTorch, or very close.
> 
> At the moment of creation of the logo, I asked Soumith about PyTorch text font to make the same. He didn't know :) So, I picked Ubuntu font that IMO was close to PyTorch...

It clearly does look close, but it's noticeably thicker I think (I like fonts). Using whatfontis.com I can find close fonts, but no exact match. Edit: this is actually FreightSans ! (https://fonts.adobe.com/fonts/freight-sans, then type PyTorch)

**Comment by vfdev-5** [comment]
Nice finding ! 

Screen Shot 2019-09-17 at 01 06 27
Screen Shot 2019-09-17 at 01 09 30

**Comment by bosr** [comment]
Hi, I styled the versions menu (needs a small PR on SCVersioning, opened on your repo). I also updated the logo with FreightSans Pro (we can iterate over that in this PR or later, as you see fit). That version is live on my gh-pages.

Caveat: please note that the logo is being overridden only in the versions that have it in their source tree, the same story again ;)

Cheers!

**Comment by vfdev-5** [comment]
@bosr perfect !

If you wish I can update SCVersioning such that we pass _templates, _static, css etc. just tell me what to pass :)

**Comment by bosr** [comment]
Thanks @vfdev-5! I should have some time tomorrow. Cheers

**Comment by vfdev-5** [comment]
@bosr actually, I found how to do this. This works locally : https://github.com/vfdev-5/ignite/commit/5742a3317326cc4948c8fb44c555816b3920ed16

We just need to make logo a bit larger. How did you picked these values ?
```
  height: 33px;
  width: 108px;
  background-image: url("../img/ignite-logo-dark.svg");
  background-size: 108px 33px;
```

**Comment by bosr** [comment]
> @bosr actually, I found how to do this. This works locally : [vfdev-5@5742a33](https://github.com/vfdev-5/ignite/commit/5742a3317326cc4948c8fb44c555816b3920ed16)
> 
> We just need to make logo a bit larger. How did you picked these values ?
> 
> ```
>   height: 33px;
>   width: 108px;
>   background-image: url("../img/ignite-logo-dark.svg");
>   background-size: 108px 33px;
> ```

Cool, thanks! I tried live in the browser dev inspector. Please adjust!

**Comment by bosr** [comment]
yummy, I'm now eager to see it live!

**Comment by vfdev-5** [comment]
me too :) 
anyway great job done @bosr ! Thanks a lot for such awesome contribution !

**Comment by bosr** [comment]
Nice, thank you! I'm @bosr_ (I'm just a follower of the DL community, I almost never tweet).

Cheers, it was a pleasure working with you. See you soon for other PRs

**Comment by bosr** [comment]
@vfdev-5, by the way, I think I should delete my gh-pages branch, to avoid confusion. Right?

**Comment by bosr** [comment]
Do you have an ETA for the docs push? v0.3 or before?

**Comment by vfdev-5** [comment]
> @vfdev-5, by the way, I'm about to delete my gh-pages branch, to avoid confusion. Right?

Yes, you can delete your gh-pages branch. No problems.

> Do you have an ETA for the docs push? v0.3 or before?

Seems like travis has no resources at the moment : https://travis-ci.org/pytorch/ignite/builds/586756530

Concerning v0.3.0 release, we have project for https://github.com/pytorch/ignite/projects/6
and there are still some issues to fix.

**Comment by bosr** [comment]
> Concerning v0.3.0 release, we have project for https://github.com/pytorch/ignite/projects/6
> and there are still some issues to fix.

Yes, I saw your board, it's nice. I had spotted a few issues I found interesting (the good 1st issues).

**Comment by bosr** [comment]
It’s live! Thanks a lot for your help!

**Comment by vfdev-5** [comment]
Hey @bosr I was wondering whether you would be interested in helping us (me and @Evpok) to improve ignite's poster for PyTorch DevCon 2019 ?

**Comment by bosr** [comment]
Hi vfdev, thanks for the proposal. I’m glad to help, but I can’t spend much time on this. I’ve just submitted my application for slack ;)

Cheers!
Romain

**Pull request merged**
