### PR TITLE
fix Remove useless prints from tests

### LINKED ISSUE #1240: Remove useless prints from tests
## 🚀 Feature

Some tests contain `print`s that probably were used for debugging and were not removed. It is better to remove them.

For example, 
https://github.com/pytorch/ignite/blob/44c60564bf59a3028ab89091cbd3d73def8be86f/tests/ignite/contrib/engines/test_common.py#L71

https://github.com/pytorch/ignite/blob/44c60564bf59a3028ab89091cbd3d73def8be86f/tests/ignite/contrib/engines/test_common.py#L244

https://github.com/pytorch/ignite/blob/44c60564bf59a3028ab89091cbd3d73def8be86f/tests/ignite/contrib/handlers/test_param_scheduler.py#L631

etc

### PR DESCRIPTION
**Pull request by Yogendra0Sharma**
Fixes #1240 
Remove useless prints from tests

### CODE REVIEW

**Comment by sdesrozis** [comment]
@Yogendra0Sharma  Thank you!

One more 

https://github.com/pytorch/ignite/blob/ddb1eab80efb5404e9887a1ce31d21d6b2fd3957/tests/ignite/metrics/test_metric.py#L784

and maybe 

https://github.com/pytorch/ignite/blob/ef5fbd6cdd467f41428e1711e6817a8ecc538b74/tests/ignite/distributed/utils/test_serial.py#L12

https://github.com/pytorch/ignite/blob/00ef5710b10191f412d33b32baa1e01148b985ff/tests/ignite/engine/test_deterministic.py#L182

What do you think ?

**Comment by vfdev-5** [comment]
@Yogendra0Sharma any update on this ?

**Comment by vfdev-5** [comment]
@Yogendra0Sharma are you still interested in working on this PR ? 
Otherwise, I'll close it

**Comment by vfdev-5** [comment]
I close the PR as uncompleted.

**Pull request closed without merging**
