### PR TITLE
Notebook Example - CNN for Text Classification

### PR DESCRIPTION
**Pull request by anmolsjoshi**
Related to #367 

Description:
Provide example in the form of Jupyter Notebook for using CNN for Text Classification on IMDB dataset.

Check list:
* [ ] New tests are added (if a new feature is modified)
* [ ] New doc strings: text and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by anmolsjoshi** [comment]
@vfdev-5 please review example.

**Comment by anmolsjoshi** [comment]
@vfdev-5 i have incorporated your comments, I'll look into google colab.

**Comment by anmolsjoshi** [comment]
@vfdev-5 I have updated the notebook per your comments, let me what your thought are.

**Comment by vfdev-5** [comment]
@anmolsjoshi thanks !

**Pull request merged**
