### PR TITLE
TrainsLogger semantic segmentation example

### PR DESCRIPTION
**Pull request by bmartinn**
Following the discussion at #1057 

Description:
Add TrainsLogger Example to the semantic segmentation tutorial.

Check list:
* [x] New tests are added (if a new feature is added)
* [x] New doc strings: description and/or example code are in RST format
* [x] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@bmartinn thanks for the PR ! 
What we plan to do next from our side
- update these examples with our recent distributed module and coming one
- setup an online Trains server (as discussed in a comment and with Moses)
- run thoses experiments on various infras with logging to the online server.

cc @sdesrozis

**Comment by sdesrozis** [comment]
@bmartinn Thank you for this excellent improvement of our reference segmentation usecase 👍🏻 let’s see the next 😊

**Comment by bmartinn** [comment]
@sdesrozis any idea why the TPU test is failing? (is it related to the PR?)

**Comment by sdesrozis** [comment]
No, it’s not related. Let’s restart.

**Pull request merged**
