### PR TITLE
docs: link to master about page [skip ci]

### PR DESCRIPTION
**Pull request by ydcjeff**
Fixes #{issue number}

Description:

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@ydcjeff we can't test that on netlify as [skip ci] :(

**Review by vfdev-5 — APPROVED** [review]
Let's see. Thanks @ydcjeff

**Comment by ydcjeff** [comment]
@vfdev-5 Docs build will pass, but `linkcheck` job will fail since it has `-W` which is "treats warning as error"

**Comment by vfdev-5** [comment]
@ydcjeff can we ignore this single warning somehow otherwise it is annoying to have a failing test...

**Pull request merged**
