### PR TITLE
improve cohen kappa tests

### PR DESCRIPTION
**Pull request by KickItLikeShika**
Our 2nd PR to improve `ignite.contrib.metrics` module. I have updated the tests of `cohen_kappa` as we have done with [AveragePrecision](https://github.com/pytorch/ignite/blob/master/tests/ignite/contrib/metrics/test_average_precision.py)
Check list:

- [x] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by KickItLikeShika** [comment]
@vfdev-5, there is weird problem! some tests never started and now i got 2 tests failed! it took so long to start the workflow

**Comment by vfdev-5** [comment]
@KickItLikeShika probably, an internal GA issue. I restart evrything.

**Comment by KickItLikeShika** [comment]
@vfdev-5 is this related https://github.com/pytorch/ignite/pull/1760/checks?check_run_id=2068344523? or is it just because of the GA issue?

**Comment by vfdev-5** [comment]
@KickItLikeShika I think we can ignore these failures

**Comment by KickItLikeShika** [comment]
@vfdev-5, sounds good! i will keep working on the other metrics, Thanks!

**Pull request merged**
