### PR TITLE
[Step 1/4: Ready for review] Add Engine.has_event_handler

### PR DESCRIPTION
**Pull request by zasdfgbnm**
As discussed in https://github.com/pytorch/ignite/pull/323#issuecomment-436819733

@vfdev-5 Which do you think we should have?
`has_handler(func)`, or `has_event_handler(event_name, func)`, or both?

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
Where is the CI?

**Comment by zasdfgbnm** [comment]
@vfdev-5 I finally make it `has_event_handler(func, event_name=None)`. I choose `has_event_handler` instead of `has_handler` just to be consistent with `add_event_handler`. Let me know if you think `has_handler` is better.

**Comment by vfdev-5** [comment]
@zasdfgbnm I think it is ok for the name. Looks good.

@alykhantejani @jasonkriss please review. This feature is needed as discussed in #323 (the link in the description above) to verify if a handler is already attached and to be able to attach a handler only once.

**Comment by zasdfgbnm** [comment]
Kindly ping @alykhantejani , no hurry, just in case you forget this

**Comment by zasdfgbnm** [comment]
Next step is: https://github.com/pytorch/ignite/pull/326

**Pull request merged**
