### PR TITLE
Fix metaclass of metric for python3

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Fixes https://github.com/pytorch/ignite/issues/337

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
@vfdev-5 Do you think it worth a new test case for this?

**Comment by vfdev-5** [comment]
@zasdfgbnm yes, please add a test what would fail without this fix with assert raise when an abstract class is instanciated.

**Comment by zasdfgbnm** [comment]
@vfdev-5 test added

**Comment by vfdev-5** [comment]
@zasdfgbnm please update [meta.yaml](https://github.com/pytorch/ignite/blob/3f57ee52d233b39df926c0aef4d3c23730f2a821/conda.recipe/meta.yaml) too

**Comment by vfdev-5** [comment]
@alykhantejani, @jasonkriss we add `six` as new dependency, any objections ?

**Comment by zasdfgbnm** [comment]
@vfdev-5 done

**Comment by jasonkriss** [comment]
Can we maybe utilize https://github.com/pytorch/pytorch/blob/master/torch/_six.py#L54 rather than adding `six` as a dependency?

**Comment by zasdfgbnm** [comment]
@jasonkriss Do you mean something like:

```
from torch._six import with_metaclass
```

Or like pytorch did, just copy that file to ignite? `_six` is not in pytorch public API and might be removed in the future.

**Comment by alykhantejani** [comment]
Let's not rely on pytorch's import as its a private module `_six`. However, we can follow there approach and have an `ignite._six` and just copy the relevant functions we need (and the copyright notice)?

**Comment by alykhantejani** [comment]
we can, but seems overkill (also keeps ignite lightweight). We could just cp pytorch/_six.py as it contains what we need. I'm open to including other dependencies in general, but I don't think we need/use much of six, and pytorch has already copied this function across

**Comment by zasdfgbnm** [comment]
I also prefer not copying file, but use dependency instead. But I'm OK with any decision.

**Comment by jasonkriss** [comment]
If we start to need a lot of functionality from `six`, then I think it's fine to add it as a dependency. That being said, in this case, it's 5 lines of code, so I think it'd preferable to add an `ignite._six` with just the `with_metaclass` implementation.

**Comment by vfdev-5** [comment]
Okay, let's merge it like this

**Comment by alykhantejani** [comment]
Thanks @zasdfgbnm!

**Pull request merged**
