### PR TITLE
return relevant history from 'run' and 'validate'

### PR DESCRIPTION
**Pull request by jasonkriss**
This is purely for convenience but I think it is quite common that people will want to access the history right after. I'm already finding this in my own work.

### CODE REVIEW

**Comment by fmassa** [comment]
Just realized that we might want to wait for #54 to be merged before merging this

**Comment by jasonkriss** [comment]
@fmassa My personal use case is actually a lil different. I have a setup where models get trained to completion (a predefined number of epochs) and then are evaluated/tested once at the very end.

Currently, I do something like this,

```python
```

**Comment by alykhantejani** [comment]
@jasonkriss @fmassa let's try and get #54 merged and then we can re-visit/ update this PR. Sorry for the delay on this

**Comment by alykhantejani** [comment]
Closing this as the API has changed a lot and I think we can revisit this with the new State object being introduced in #80. Please let me know if you think this should be kept open and I can re-open

**Pull request closed without merging**
