### PR TITLE
Feature step param scheduler issue 2488

### LINKED ISSUE #2488: Add StepParamScheduler feature
## 🚀 Feature

I propose to add `StepParamScheduler` to `ignite.handlers.param_scheduler`. It is basically used to multiply a parameter
by a fixed factor every `step_size` steps. This can be done by subclassing `ParamScheduler` and implementing its simple logic.

This class is commonly used, so it's good to have it in the Ignite.

### PR DESCRIPTION
**Pull request by sadra-barikbin**
Fixes #2488 

Description:
This is the proposed implementation for `StepParamScheduler` feature.
Check list:

- [x] New tests are added (if a new feature is added)
- [x] New doc strings: description and/or example code are in RST format
- [x] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@sadra-barikbin I would suggest to pause on this PR as we haven't decided to move forward with this feature request. Let's work on something else. For example: https://github.com/pytorch/ignite/issues/2328 (this one is not assigned to anyone)
What do you think ?

**Comment by sadra-barikbin** [comment]
@vfdev-5 
Sure, but it has an open pull request itself. Do you mean to continue on its pull request? Is it not finished?

**Comment by vfdev-5** [comment]
> Sure, but it has an open pull request itself. Do you mean to continue on its pull request? Is it not finished?

@sadra-barikbin yes, it is not finished and probably wont be finished. You can either start from scratch or take something useful from that PR.

**Comment by vfdev-5** [comment]
@sadra-barikbin can we close this PR ?

**Comment by sadra-barikbin** [comment]
Yes, I did.

**Pull request closed without merging**
