### PR TITLE
Add get test cases

### PR DESCRIPTION
**Pull request by KickItLikeShika**
Update the way how we generate tests in [AveragePrecision](https://github.com/pytorch/ignite/blob/master/tests/ignite/contrib/metrics/test_average_precision.py) and [CohenKappa](https://github.com/pytorch/ignite/blob/master/tests/ignite/contrib/metrics/test_cohen_kappa.py).

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@trsvchn could you please take a look at this failure : https://github.com/pytorch/ignite/pull/1774/checks?check_run_id=2095808150#step:13:10
Here on MacOSX it still tries to download from the original server with 503 error

**Comment by trsvchn** [comment]
@vfdev-5 Huh, But here it works:
https://github.com/trsvchn/ignite/actions/runs/646413478

**Comment by vfdev-5** [comment]
Thanks @trsvchn !

**Comment by KickItLikeShika** [comment]
Thanks @trsvchn, It works fine now!

**Review by vfdev-5 — APPROVED** [review]
Thanks @KickItLikeShika !

**Pull request merged**
