### PR TITLE
Extend LRFinder

### LINKED ISSUE #1912: Move param handlers to core part
## 🚀 Feature

As discussed in https://github.com/Project-MONAI/MONAI/pull/1949#issuecomment-815283287 moving https://github.com/pytorch/ignite/blob/master/ignite/contrib/handlers/param_scheduler.py to the core part: https://github.com/pytorch/ignite/tree/master/ignite/handlers could be great addition for users, apps and toolkits which do not use contrib module (e.g. MONAI).

While moving the code, we would like to ensure BC-compatibilty for at least one future release. Once the code has been moved we can put deprecation message for classes and methods inside contrib module. `contrib/handlers/param_scheduler.py` will be removed in v0.6.0.

A follow-up feature to this feature request could be enlarging the scope of `ParamScheduler` to scheduling any parameter (e.g. hyperparameters) like it is done in MONAI: https://github.com/Project-MONAI/MONAI/pull/1949

cc @danieltudosiu

### PR DESCRIPTION
**Pull request by KickItLikeShika**
This PR contains some updates:
- Moved `LRFinder` to core.
- Updated the way we find the suggested learning rate: for more details check this notebook: https://colab.research.google.com/drive/1_siUuBjZkHVc_PGS28gmF0SYzKDgMbKJ?usp=sharing#scrollTo=naYcP7kvRAXq (Thanks for @vfdev-5 for helping me)
- Added a red dot to show the suggested learning rate (provided in the notebook)
- Added MNIST tests for LRFinder.

Check list:

- [x] New tests are added (if a new feature is added)
- [x] New doc strings: description and/or example code are in RST format
- [x] Documentation is updated (if required)

### CODE REVIEW

**Comment by KickItLikeShika** [comment]
All the commas additions and deletions have been done with `black` while commiting

**Comment by vfdev-5** [comment]
@KickItLikeShika thanks for the PR ! However, let's do things 1 by 1. Let's remove moving param scheduler to core from here.

**Comment by KickItLikeShika** [comment]
@vfdev-5 I have been trying to move `ParamScheduler` back to contrib but I get this error when I try to run the tests 
```
Traceback:
/home/kickitlikeshika/anaconda3/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/ignite/handlers/test_lr_finder.py:10: in <module>
    from ignite.engine import Events, create_supervised_trainer
ignite/__init__.py:3: in <module>
    import ignite.engine
ignite/engine/__init__.py:10: in <module>
    from ignite.metrics import Metric
ignite/metrics/__init__.py:7: in <module>
    from ignite.metrics.frequency import Frequency
ignite/metrics/frequency.py:7: in <module>
    from ignite.handlers.timing import Timer
ignite/handlers/__init__.py:7: in <module>
    from ignite.handlers.lr_finder import FastaiLRFinder
ignite/handlers/lr_finder.py:15: in <module>
    from ignite.contrib.handlers.param_scheduler import LRScheduler, PiecewiseLinear
ignite/contrib/handlers/__init__.py:1: in <module>
    from ignite.contrib.handlers.clearml_logger import ClearMLLogger
ignite/contrib/handlers/clearml_logger.py:24: in <module>
    from ignite.handlers import global_step_from_engine
E   ImportError: cannot import name 'global_step_from_engine' from partially initialized module 'ignite.handlers' (most likely due to a circular import) (ignite/ignite/handlers/__init__.py)
```
Can you help me please?

**Comment by sdesrozis** [comment]
I would prefer fix #837 and move LRFinder to core in another PR. It would be a shame that BC issues were mixed to functional issues. 

I agree with @vfdev-5, step by step.

**Comment by KickItLikeShika** [comment]
Me and @vfdev-5 agreed on solving #837 in two PRS:
1- Fix the suggestion and add the red dot then move it to core
2- Work on DDP
That's the first PR to fix the first point, but I saw #1912 yesterday and I thought It would be good to move it as well, and everything was working fine but now I got the issues I mentioned above. I'm open to hear from you, I can continue on this or I can close this one and divide It to 3 PRs:
1- Fix the learning rate suggestion and add the red dot
2- Move the LRFinder to core
3- Work on DDP

**Comment by sdesrozis** [comment]
I didn't know that it had been discussed in details with @vfdev-5. I suggest to do as you planned with @vfdev-5, I don't want to add noise to your actions. I understand that this PR do not fix #837, maybe change the description and the title of the PR would be sufficient.

**Pull request closed without merging**
