### PR TITLE
Fixes #1258

### LINKED ISSUE #1258: Replace mp.spawn by mp.start_processes for native comp model
## 🚀 Feature

As torch native `mp.spawn` does not work on Colab with `start_method='spawn'`, but seem to work with `start_method='fork'` if using `mp.start_processes`. Idea is to simply replace `mp.spawn` by `mp.start_processes` here : 
https://github.com/pytorch/ignite/blob/c6673710fcd78949e0bf203ed9155e82ef639061/ignite/distributed/comp_models/native.py#L282-L285

### PR DESCRIPTION
**Pull request by vfdev-5**
Fixes #1258

Description:
- Replaced mp.spawn by mp.start_processes for native comp model

Check list:
* [x] New tests are added (if a new feature is added)
* [x] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by sdesrozis** [comment]
Does it fix the lag when `mp.spawn` was used ?

**Comment by vfdev-5** [comment]
@sdesrozis which lag you think about ?

**Comment by sdesrozis** [comment]
The fact that dataloaders were very long on first loading. Maybe I'm wrong about that.

**Comment by vfdev-5** [comment]
No, it does not

**Pull request merged**
