### PR TITLE
update cifar10 example: validation with amp

### LINKED ISSUE #1666: Update cifar10 example, validation with amp
Currently, we provide AMP option for the training, but model's evaluation still run on plain f32. Recently, we merged [transformers example](https://github.com/pytorch/ignite/tree/master/examples/contrib/transformers) where evaluation takes amp into account : https://github.com/pytorch/ignite/blob/master/examples/contrib/transformers/main.py#L367

The idea is to make cifar10 example compatible as transformers example:

Replace 
https://github.com/pytorch/ignite/blob/7753eabc5af8bed2cca4713805613adfbc460a8e/examples/contrib/cifar10/main.py#L86-L87

by 
https://github.com/pytorch/ignite/blob/7753eabc5af8bed2cca4713805613adfbc460a8e/examples/contrib/transformers/main.py#L88-L89

and create similar `create_evaluator` helper method.

### PR DESCRIPTION
**Pull request by Moh-Yakoub**
Fixes #1666

Description: Update cifar10 example, use validation with amp 

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@Moh-Yakoub any particular reason for closing this PR ?

**Comment by Moh-Yakoub** [comment]
> @Moh-Yakoub any particular reason for closing this PR ?

I didn't intent to publish the PR - Did by mistake - before testing it manually.
I will publish the PR once I test manually.

**Comment by vfdev-5** [comment]
Sounds good ! 
I'm just realized that we do not put any check for [`with_amp` argument](https://github.com/Moh-Yakoub/ignite/blob/8db7704785634cf4c1db3a5b3a011a529094205e/examples/contrib/cifar10/main.py#L158) and the [backend](https://github.com/Moh-Yakoub/ignite/blob/8db7704785634cf4c1db3a5b3a011a529094205e/examples/contrib/cifar10/main.py#L152). Could you please add somewhere [here](https://github.com/Moh-Yakoub/ignite/blob/8db7704785634cf4c1db3a5b3a011a529094205e/examples/contrib/cifar10/main.py#L196) and assertion that if backend is "xla-tpu" and "with_amp is True" then raise an RuntimeError saying that `with_amp` should be False if backend is xla. Thanks

**Comment by Moh-Yakoub** [comment]
Perfect, will add that.

by the way, For manually testing this I am just doing a `python main.py run` and making sure I am not breaking anything.

Is there any additional tests that I can do locally.

Thanks

**Comment by vfdev-5** [comment]
It will be tested on our CI once merged to the master on 1 and 2 GPUs. I think it is fine to test as you suggest.

> Is there any additional tests that I can do locally.

It depends on your infrastructure but it is not that critical for this PR. You can also try on the colab like here: https://colab.research.google.com/drive/1E9zJrptnLJ_PKhmaP5Vhb6DTVRvyrKHx (just make sure to download your fork instead of the master)

**Pull request closed without merging**
