### PR TITLE
Fix footer layout

### PR DESCRIPTION
**Pull request by trsvchn**
Improves #1653 

Description:

The main aim is to achieve better layout (to put text and badge in a same row) with table to fit mobile screens and on zooming.

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Review by vfdev-5 — APPROVED** [review]
Awesome, look very nice now ! Thanks Taras !
Can we merge it or you'd like to play around a bit more ?

**Comment by trsvchn** [comment]
@vfdev-5 Yes, Let's merged it! It's too much HTML+CSS for the Friday evening! :D

**Comment by vfdev-5** [comment]
Yeah ! Let's take some refreshers and relax :) 
Btw, let me know if you received or not yet the stickers (sent them Feb 5th)

**Comment by trsvchn** [comment]
Sure! Thanks!)

**Pull request merged**
