### PR TITLE
Changed ProgressBar init's type annotation to accept None

### LINKED ISSUE #2540: Bar format is `str` but should be  `Optional[str]` in ignite.contrib.handlers.tqdm_logger.ProgressBar
## 🐛 Bug description

`ignite.contrib.handlers.tqdm_logger.ProgressBar` can accept `None` in the `bar_format` initialization argument (as documented), but this is not reflected in the type annotation.

https://github.com/pytorch/ignite/blob/82a929d3e452ccaba8c7767148231e741b6335e5/ignite/contrib/handlers/tqdm_logger.py#L120

### PR DESCRIPTION
**Pull request by Davidportlouis**
Fixes #2540

Description: 

* Added `None` to `bar_format` type annotation in initialization argument of `ignite.contrib.handlers.tqdm_logger.ProgressBar`

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Review by vfdev-5 — APPROVED** [review]
Thanks @Davidportlouis , lgtm. Let's see if CI is passing and then we can merge it

**Comment by vfdev-5** [comment]
@Davidportlouis code formatting checks are not passing: https://github.com/pytorch/ignite/runs/5858540569?check_suite_focus=true#step:11:64

Please reformat the code according to https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md#formatting-code
Thanks

**Comment by Davidportlouis** [comment]
> @Davidportlouis code formatting checks are not passing: https://github.com/pytorch/ignite/runs/5858540569?check_suite_focus=true#step:11:64
> 
> Please reformat the code according to https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md#formatting-code Thanks

Fixed it

**Comment by sdesrozis** [comment]
@Davidportlouis Tests are still failing because of string mismatch. Could you have a look please ? It would be great to run the tests locally before committing.

**Comment by Davidportlouis** [comment]
> @Davidportlouis Tests are still failing because of string mismatch. Could you have a look please ? It would be great to run the tests locally before committing.

Sure i'll check it and run tests locally

**Comment by Davidportlouis** [comment]
> > @Davidportlouis Tests are still failing because of string mismatch. Could you have a look please ? It would be great to run the tests locally before committing.
> 
> Sure i'll check it and run tests locally

Fixed the string formatting issue, some tests (resume based tests) in `tests/ignite/engine/test_deterministic.py` are failing locally due to OSError - Too many open files. Other than that all tests including tests for tqdm_logger.py are passing

**Pull request merged**
