### PR TITLE
Enable footer for the docs

### LINKED ISSUE #1649: Create a footer on main docs site
## 📚 Documentation

It would be helpful to enable a footer on the docs site: https://pytorch.org/ignite/ where we can keep current mentions like 
-  © Copyright 2021, PyTorch-Ignite Contributors.
- Built with Sphinx using a theme provided by Read the Docs. 

and should place a badge from https://www.netlify.com/press/#badges . For example, this one : 

  <a href="https://www.netlify.com">
    Deploys by Netlify
  </a>

I assume that we can tweak footer part from https://github.com/pytorch/ignite/blob/master/docs/source/_templates/layout.html#L304

@trsvchn could you please help us with this improvement ?

### PR DESCRIPTION
**Pull request by trsvchn**
Fixes #1649 

Description:

I think the footer added here:

https://github.com/pytorch/ignite/blob/b1044d024b2150bcd5e439633ada41e24df281d7/docs/source/_templates/layout.html#L251

Moreover, "Built with Sphinx using a theme provided by Read the Docs." is hard coded in `footer.html` theme's template.

So, I think we can override `footer.html` with netlify badge.

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@trsvchn thanks for hacking it :) Looks good ! I wonder also if it could be difficult to set the badge on the same line as the copyright and "Built with Sphinx ..." ?

**Comment by trsvchn** [comment]
This is the result of footer tweaking.

Screenshot from 2021-02-19 18-00-29

**Comment by vfdev-5** [comment]
Thanks a lot @trsvchn ! Looks great so far!

**Review by vfdev-5 — APPROVED** [review]
Great !

**Pull request merged**
