### PR TITLE
Add anomaly detection context manager to catch loss nan and errors in…

### PR DESCRIPTION
**Pull request by vfdev-5**
… backward pass

Fixed warning in test due to deprecated arg

Addresses #201

### CODE REVIEW

**Comment by vfdev-5** [comment]
Run a benchmarking with [ignite-examples/cifar10](https://github.com/vfdev-5/ignite-examples/tree/master/classification/cifar_10)
and it is true that if detect anomaly is enabled single epoch training is ~2 times increased:
Training VGG16BN on Cifar10 : ~22 sec/epoch VS ~52-57 sec/epoch

Here are logs of two runs:

### With detect anomaly 
```
python3 cifar10_train_playground.py --model vgg16_bn --batch_size=32 --num_workers=8 --epochs=5 --log_interval=1300 --detect_anomaly
```
and 
```
2018-07-27 12:39:07,155|Cifar10 Playground: Train|INFO|         
        Training configuration:
            Model: vgg16_bn
            Image augs: imgaugs/basic.py
            Train batch size: 32
            Val batch size: 100
            Number of workers: 8
            Number of epochs: 5
            Optimizer: adam
            Learning rate: 0.0001
            Learning rate update every : 1 epoch(s)
            Exp lr scheduler gamma: 0.9
                restart every: 10
                restart factor: 1.5
                init lr factor: 0.5
            Reduce on plateau: 10
            Early stopping patience: 20
            Output folder: output/training_vgg16_bn_20180727_1239        
    
2018-07-27 12:39:15,255|Cifar10 Playground: Train|INFO| Detect anomaly: True
2018-07-27 12:39:15,267|Cifar10 Playground: Train|INFO| Start training: 5 epochs
2018-07-27 12:39:15,268|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=5
2018-07-27 12:40:12,090|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:56
2018-07-27 12:40:12,092|Cifar10 Playground: Train|INFO| One epoch training time (seconds): 56.62031644163653
2018-07-27 12:40:12,092|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:40:19,308|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:07
2018-07-27 12:40:19,315|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:07
2018-07-27 12:40:19,315|Cifar10 Playground: Train|INFO| Training Results - Epoch: 1  Avg accuracy: 0.4431 Avg loss: 1.4733
2018-07-27 12:40:20,838|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:40:22,455|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:01
2018-07-27 12:40:22,606|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:01
2018-07-27 12:40:22,607|Cifar10 Playground: Train|INFO| Validation Results - Epoch: 1  Avg accuracy: 0.4347 Avg loss: 1.4793
2018-07-27 12:41:21,747|ignite.engine.engine.Engine|INFO| Epoch[2] Complete. Time taken: 00:00:57
2018-07-27 12:41:21,748|Cifar10 Playground: Train|INFO| One epoch training time (seconds): 57.46802546270192
2018-07-27 12:41:21,749|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:41:29,081|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:07
2018-07-27 12:41:29,082|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:07
2018-07-27 12:41:29,082|Cifar10 Playground: Train|INFO| Training Results - Epoch: 2  Avg accuracy: 0.5376 Avg loss: 1.2493
2018-07-27 12:41:30,628|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:41:32,008|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:01
2018-07-27 12:41:32,113|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:01
2018-07-27 12:41:32,113|Cifar10 Playground: Train|INFO| Validation Results - Epoch: 2  Avg accuracy: 0.5283 Avg loss: 1.2770
2018-07-27 12:42:26,115|ignite.engine.engine.Engine|INFO| Epoch[3] Complete. Time taken: 00:00:52
2018-07-27 12:42:26,117|Cifar10 Playground: Train|INFO| One epoch training time (seconds): 52.216374579351395
2018-07-27 12:42:26,117|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:42:33,491|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:07
2018-07-27 12:42:33,493|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:07
2018-07-27 12:42:33,493|Cifar10 Playground: Train|INFO| Training Results - Epoch: 3  Avg accuracy: 0.6137 Avg loss: 1.0673
2018-07-27 12:42:34,997|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:42:36,364|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:01
2018-07-27 12:42:36,459|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:01
2018-07-27 12:42:36,460|Cifar10 Playground: Train|INFO| Validation Results - Epoch: 3  Avg accuracy: 0.5916 Avg loss: 1.1203
2018-07-27 12:43:34,679|ignite.engine.engine.Engine|INFO| Epoch[4] Complete. Time taken: 00:00:56
2018-07-27 12:43:34,681|Cifar10 Playground: Train|INFO| One epoch training time (seconds): 56.5373103315942
2018-07-27 12:43:34,681|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:43:42,143|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:07
2018-07-27 12:43:42,144|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:07
2018-07-27 12:43:42,144|Cifar10 Playground: Train|INFO| Training Results - Epoch: 4  Avg accuracy: 0.6732 Avg loss: 0.9013
2018-07-27 12:43:43,613|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:43:45,003|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:01
2018-07-27 12:43:45,118|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:01
2018-07-27 12:43:45,118|Cifar10 Playground: Train|INFO| Validation Results - Epoch: 4  Avg accuracy: 0.6554 Avg loss: 0.9664
2018-07-27 12:44:43,065|ignite.engine.engine.Engine|INFO| Epoch[5] Complete. Time taken: 00:00:56
2018-07-27 12:44:43,066|Cifar10 Playground: Train|INFO| One epoch training time (seconds): 56.253947474993765
2018-07-27 12:44:43,067|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:44:50,383|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:07
2018-07-27 12:44:50,384|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:07
2018-07-27 12:44:50,384|Cifar10 Playground: Train|INFO| Training Results - Epoch: 5  Avg accuracy: 0.7108 Avg loss: 0.7863
2018-07-27 12:44:51,873|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:44:53,291|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:01
2018-07-27 12:44:53,401|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:01
2018-07-27 12:44:53,402|Cifar10 Playground: Train|INFO| Validation Results - Epoch: 5  Avg accuracy: 0.6820 Avg loss: 0.8830
2018-07-27 12:44:54,932|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:05:39
```
### Without detect anomaly 
```
python3 cifar10_train_playground.py --model vgg16_bn --batch_size=32 --num_workers=8 --epochs=5 --log_interval=1300
```
and
```
2018-07-27 12:33:21,916|Cifar10 Playground: Train|INFO|         
        Training configuration:
            Model: vgg16_bn
            Image augs: imgaugs/basic.py
            Train batch size: 32
            Val batch size: 100
            Number of workers: 8
            Number of epochs: 5
            Optimizer: adam
            Learning rate: 0.0001
            Learning rate update every : 1 epoch(s)
            Exp lr scheduler gamma: 0.9
                restart every: 10
                restart factor: 1.5
                init lr factor: 0.5
            Reduce on plateau: 10
            Early stopping patience: 20
            Output folder: output/training_vgg16_bn_20180727_1233        
    
2018-07-27 12:33:29,972|Cifar10 Playground: Train|INFO| Detect anomaly: False
2018-07-27 12:33:29,977|Cifar10 Playground: Train|INFO| Start training: 5 epochs
2018-07-27 12:33:29,977|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=5
2018-07-27 12:33:52,358|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:22
2018-07-27 12:33:52,359|Cifar10 Playground: Train|INFO| One epoch training time (seconds): 22.190596501342952
2018-07-27 12:33:52,359|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:33:59,682|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:07
2018-07-27 12:33:59,689|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:07
2018-07-27 12:33:59,689|Cifar10 Playground: Train|INFO| Training Results - Epoch: 1  Avg accuracy: 0.4381 Avg loss: 1.4761
2018-07-27 12:34:01,227|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:34:02,939|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:01
2018-07-27 12:34:03,052|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:01
2018-07-27 12:34:03,052|Cifar10 Playground: Train|INFO| Validation Results - Epoch: 1  Avg accuracy: 0.4358 Avg loss: 1.4802
2018-07-27 12:34:26,585|ignite.engine.engine.Engine|INFO| Epoch[2] Complete. Time taken: 00:00:22
2018-07-27 12:34:26,587|Cifar10 Playground: Train|INFO| One epoch training time (seconds): 21.893717218656093
2018-07-27 12:34:26,588|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:34:33,934|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:07
2018-07-27 12:34:33,935|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:07
2018-07-27 12:34:33,935|Cifar10 Playground: Train|INFO| Training Results - Epoch: 2  Avg accuracy: 0.5523 Avg loss: 1.2061
2018-07-27 12:34:35,517|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:34:36,958|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:01
2018-07-27 12:34:37,055|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:01
2018-07-27 12:34:37,056|Cifar10 Playground: Train|INFO| Validation Results - Epoch: 2  Avg accuracy: 0.5383 Avg loss: 1.2338
2018-07-27 12:35:00,663|ignite.engine.engine.Engine|INFO| Epoch[3] Complete. Time taken: 00:00:22
2018-07-27 12:35:00,664|Cifar10 Playground: Train|INFO| One epoch training time (seconds): 21.936608841177076
2018-07-27 12:35:00,664|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:35:07,997|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:07
2018-07-27 12:35:07,998|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:07
2018-07-27 12:35:07,998|Cifar10 Playground: Train|INFO| Training Results - Epoch: 3  Avg accuracy: 0.6064 Avg loss: 1.0925
2018-07-27 12:35:09,429|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:35:10,810|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:01
2018-07-27 12:35:10,903|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:01
2018-07-27 12:35:10,903|Cifar10 Playground: Train|INFO| Validation Results - Epoch: 3  Avg accuracy: 0.5914 Avg loss: 1.1316
2018-07-27 12:35:35,010|ignite.engine.engine.Engine|INFO| Epoch[4] Complete. Time taken: 00:00:22
2018-07-27 12:35:35,011|Cifar10 Playground: Train|INFO| One epoch training time (seconds): 22.43142503593117
2018-07-27 12:35:35,012|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:35:42,573|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:07
2018-07-27 12:35:42,574|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:07
2018-07-27 12:35:42,574|Cifar10 Playground: Train|INFO| Training Results - Epoch: 4  Avg accuracy: 0.6756 Avg loss: 0.8909
2018-07-27 12:35:44,068|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:35:45,469|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:01
2018-07-27 12:35:45,526|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:01
2018-07-27 12:35:45,526|Cifar10 Playground: Train|INFO| Validation Results - Epoch: 4  Avg accuracy: 0.6526 Avg loss: 0.9584
2018-07-27 12:36:09,752|ignite.engine.engine.Engine|INFO| Epoch[5] Complete. Time taken: 00:00:22
2018-07-27 12:36:09,753|Cifar10 Playground: Train|INFO| One epoch training time (seconds): 22.5810920689255
2018-07-27 12:36:09,753|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:36:17,295|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:07
2018-07-27 12:36:17,296|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:07
2018-07-27 12:36:17,296|Cifar10 Playground: Train|INFO| Training Results - Epoch: 5  Avg accuracy: 0.7153 Avg loss: 0.7910
2018-07-27 12:36:18,773|ignite.engine.engine.Engine|INFO| Engine run starting with max_epochs=1
2018-07-27 12:36:20,201|ignite.engine.engine.Engine|INFO| Epoch[1] Complete. Time taken: 00:00:01
2018-07-27 12:36:20,277|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:00:01
2018-07-27 12:36:20,277|Cifar10 Playground: Train|INFO| Validation Results - Epoch: 5  Avg accuracy: 0.6898 Avg loss: 0.8822
2018-07-27 12:36:21,797|ignite.engine.engine.Engine|INFO| Engine run complete. Time taken 00:02:51
```

**Comment by alykhantejani** [comment]
eeek - that's quite some overhead. 

We can add it in, but as optional with default `False`

**Comment by alykhantejani** [comment]
@vfdev-5 I still think this would be good to add - just with `False` as default. Could you update the PR when you have some time?

**Comment by vfdev-5** [comment]
@alykhantejani following our discussion:

> vfdev-5: 

As we propose such option but with default behaviour `False`, wont it be better to provide a handler as discussed in the associated issue (like `TerminateOnNaN`) which can potentially have less overhead than `torch.autograd.set_detect_anomaly(True)` as the latter checks all tensors in the graph...
I agree that with a handler, user should manually add it, more code vs just set an option `True` in Engine if we use `torch.autograd.set_detect_anomaly(True)`.

> alykhantejani:

this makes more sense
a handler would be better
maybe just close this PR?

I close this PR and will create another one with `TerminateOnNaN` handler

**Pull request closed without merging**
