### PR TITLE
Auto pin_memory

### LINKED ISSUE #1128: auto_dataloader can auto set pin_memory if appropriate
## 🚀 Feature

Idea is to automatically set `pin_memory=True` if `idist.backend()` is `nccl` or default device is `cuda`.

In the code we can omit this param instead of 
https://github.com/pytorch/ignite/blob/6b88eb89cf40e3c4ebe05e0fe67f3c8013ecc5c2/examples/contrib/cifar10/main.py#L199

### PR DESCRIPTION
**Pull request by InCogNiTo124**
Fixes #1128 

Description:
Adds a new feature, if the `device` is `'cuda'`, set `pin_memory` to `True` automatically.

Check list:
* [x] New tests are added (if a new feature is added)
* [x] New doc strings: description and/or example code are in RST format
* [x] Documentation is updated (if required)

### CODE REVIEW

**Comment by InCogNiTo124** [comment]
This ought to be the best commit I've ever pushed

**Comment by vfdev-5** [comment]
@InCogNiTo124 it is almost perfect PR :)
Just to confirm if user set `pin_memory=False`, we rewrite it to True, right ?
I think it would be better to set it True only in case if user doesn't provide anything.

**Comment by InCogNiTo124** [comment]
> Just to confirm if user set `pin_memory=False`, we rewrite it to True, right ?
I think that's already the case:

L101: `kwargs["pin_memory"] = kwargs.get("pin_memory", idist.device() == "cuda")`

What ever the user has provided for `pin_memory` (whether `True` or `False`) is passed directly with this. Only if the user hasn't provided anything, will the default parameter be returned, which is set to `True` if cuda is applicable, and `False` otherwise.

Please correct me if I am wrong though.

**Comment by vfdev-5** [comment]
No, you are right, that's correct !

**Comment by InCogNiTo124** [comment]
Not a problem :)

**Pull request merged**
