### PR TITLE
docs: rm type hints in ignite.metrics (4)

### LINKED ISSUE #1665: Use autodoc_typehints = "description" in conf.py
## 📚 Documentation

EDITED HERE: As a help wanted issue, please, see below comment https://github.com/pytorch/ignite/issues/1665#issuecomment-783240506 on what remains to do here. Thanks 

If there are many arguments in class/function/method, it's a little hard to read/scan all arguments (due to typehints).
Although there is a `Parameters` section, there might be missing some arguments (rarely though).
And we are duplicating type hints work in both signatures and docstring. Writing once can make less work on authors and less type hints mismatch can occur.

If we can remove type hints, it can be a little easier to read, and showing type hints only in `Parameters` section.

For example:
Before:
Screen Shot 2021-02-21 at 22 52 16
After:
Screen Shot 2021-02-21 at 22 51 40

Changing to this docs style needs a little work. It needs to 
- add
```py
autoclass_content = "both"
autodoc_typehints = "description"  # new in sphinx 3.1
```
those lines in `conf.py`
- removing type hints in docstring
- leaving type hints only in signatures.

Let me know what you think.
cc: @vfdev-5 @sdesrozis @trsvchn

### PR DESCRIPTION
**Pull request by ydcjeff**
Part of #1665 
Fixes #1665 
https://deploy-preview-1686--pytorch-ignite-preview.netlify.app/metrics.html

Description: 
- remove type hints in ignite.metrics
- add missing doc strings

Check list:

- [ ] New tests are added (if a new feature is added)
- [x] New doc strings: description and/or example code are in RST format
- [x] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@ydcjeff I propose to insert another PR before this one with sphinx version update and all those conf.py flags. What do you think ?

**Comment by ydcjeff** [comment]
> @ydcjeff I propose to insert another PR before this one with sphinx version update and all those conf.py flags. What do you think ?

Sounds great

**Review by vfdev-5 — APPROVED** [review]
Looks good to me! Thanks @ydcjeff 

I let others to review this PR as well

**Review by sdesrozis — APPROVED** [review]
@ydcjeff Looks good to me. Thank you, especially for adding missing docstring regarding arguments of methods.

**Pull request merged**
