### PR TITLE
unify trainer and evaluator into a single engine

### LINKED ISSUE #122: Unify Trainer and Evaluator to a single Engine
Following the discussions in #118

### PR DESCRIPTION
**Pull request by jasonkriss**
Fixes #122 

@alykhantejani @veugene I'd appreciate a review on this one.

### CODE REVIEW

**Comment by veugene** [comment]
Looks good. Perhaps the `COMPLETED` and `STARTED` events could be removed, now.

**Comment by jasonkriss** [comment]
@veugene I think there is still a use for those. For example, if you want to run some handler code only at the completion of all training.

**Comment by veugene** [comment]
@jasonkriss Yeah, that makes sense.

**Comment by alykhantejani** [comment]
Also needs merge conflict after #123 was merged

**Comment by veugene** [comment]
Great! By the way, I noticed that the conflict resolution changes re-introduce a return value to `Engine` (`self.state`) - I've previously modified the tests to extract the state from the engine instead of getting it as a return value of `run`. There were tests that verify that the `run` method returns a state; instead, these now verify that a `State` is created in the engine after a `run`.

**Comment by jasonkriss** [comment]
Is there a specific reason why we'd not want `run` to return `state`? To me, it seems like the natural thing to do.

**Comment by veugene** [comment]
To me, it seems neither natural nor unnatural. I merely removed it once there was no longer a need for it, now that `state` is an accessible property of the engine.

**Comment by jasonkriss** [comment]
@veugene 👍 gotcha.

**Pull request merged**
