### PR TITLE
ci: run `linkcheck` only on push and pull

### PR DESCRIPTION
**Pull request by ydcjeff**
fix: #2066 

Description: Run `linkcheck` job only on push and pull events

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by trsvchn** [comment]
Thanks @ydcjeff !

But I think it still will be triggered only for `master` push events, and `all` branches `pull_request` events right?

**Comment by ydcjeff** [comment]
> Thanks @ydcjeff !
> 
> But I think it still will be triggered only for `master` push events, and `all` branches `pull_request` events right?

Yes

**Comment by trsvchn** [comment]
we need smth like this, in pseudo code:

```
on:
  push:
    branches: all
  pull_request:
    branches: all
  release:
    types: [published]

jobs:
  build-deploy:
    if: github.event_name != 'pull_request' OR  (branch == master AND github.event_name == 'push')
...
  linkcheck:
    if: github.event_name == 'pull_request' || github.event_name == 'push'
```

**Comment by ydcjeff** [comment]
> we need smth like this, in pseudo code:
> 
> ```
> on:
>   push:
>     branches: all
>   pull_request:
>     branches: all
>   release:
>     types: [published]
> 
> jobs:
>   build-deploy:
>     if:  (branch == master AND github.event_name == 'push')) OR (gh.event == release)
> ...
>   linkcheck:
>     if: github.event_name == 'pull_request' || github.event_name == 'push'
> ```

Assuming we are doing `push`, `pull`, and `release`, current workflow file is doing the same as the pseudo code.

**Comment by trsvchn** [comment]
Current workflow looks like this:
```
on:
  push:
    branches: all
  pull_request:
    branches: all
  release:
    types: [published]

jobs:
  build-deploy:
    if:  (branch == master AND github.event_name == 'push')) OR (gh.event == release)
...
  linkcheck:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' AND (branch == master))
```

**Comment by ydcjeff** [comment]
Sorry, I mean this PR workflow file

**Comment by trsvchn** [comment]
Let's call it "proposed" :)

Current workflow looks like this:
```
on:
  push:
    branches: all
  pull_request:
    branches: all
  release:
    types: [published]

jobs:
  build-deploy:
    if:  (branch == master AND github.event_name == 'push') OR (gh.event == release)
...
  linkcheck:
    if: github.event_name == 'pull_request' OR (github.event_name == 'push' AND (branch == master))
```

**Review by trsvchn — APPROVED** [review]
LGTM! Thanks @ydcjeff !

**Pull request merged**
