### PR TITLE
Issue #1247

### LINKED ISSUE #1247: Remove deprecated CustomPeriodicEvent
## 🚀 Feature

It is time to remove deprecated class [CustomPeriodicEvent](https://github.com/pytorch/ignite/blob/a82d890788bf16ec61a599c32dc8d5c679e662e7/ignite/contrib/handlers/custom_events.py#L6) and corresponding related entries in the docs and the tests:
- remove file `ignite/contrib/handlers/custom_events.py`
- remove tests `tests/ignite/contrib/handlers/test_custom_events.py`
- other occurencies of `CustomPeriodicEvent` in other tests, code and [docs](https://github.com/pytorch/ignite/tree/master/docs/source)

If you would like to help the project and work on this issue, please leave a message here. For any questions or guidance, feel free to ask here as well.

### PR DESCRIPTION
**Pull request by Tawishi**
Fixes #1247 

Description: Remove deprecated CustomPeriodicEvent

### CODE REVIEW

**Comment by Tawishi** [comment]
@vfdev-5 Could you please help me figure why these tests are failing? 
Also, any more files(code, docs etc) where _CustomPeriodicEvent_ is to be removed. I could only find one.

**Comment by vfdev-5** [comment]
@Tawishi there is an import to remove from tqdm progressbar : https://travis-ci.org/github/pytorch/ignite/jobs/721788864#L1445

**Review by vfdev-5 — COMMENTED** [review]
@Tawishi please find and remove all occurences of `CustomPeriodicEvent` in the project:
- tests
- [docs](https://github.com/pytorch/ignite/tree/master/docs/source)

Thanks !

**Comment by vfdev-5** [comment]
@Tawishi looks better. Please, remove also 
```txt
custom_events
-------------

.. automodule:: ignite.contrib.handlers.custom_events
   :members:
```
from https://github.com/Tawishi/ignite/blob/issue-1247/docs/source/contrib/handlers.rst

You try to build locally the docs and inspect if your docs modifications are correct:
```
cd docs
pip install -r requirements.txt
make html
cd build/html 
python -m http.server 8080
```
open in the browser `0.0.0.0:8080`

**Comment by Tawishi** [comment]
> @Tawishi looks better. Please, remove also
> 
> ```
> custom_events
> -------------
> 
> .. automodule:: ignite.contrib.handlers.custom_events
>    :members:
> ```
> 
> from https://github.com/Tawishi/ignite/blob/issue-1247/docs/source/contrib/handlers.rst
> 
> You try to build locally the docs and inspect if your docs modifications are correct:
> 
> ```
> cd docs
> pip install -r requirements.txt
> make html
> cd build/html 
> python -m http.server 8080
> ```
> 
> open in the browser `0.0.0.0:8080`

Okay, will do.

**Comment by Tawishi** [comment]
It is running fine. :+1: 

Used
```
python3 -m http.server 8080
```
instead of the above-mentioned command.

There are still some *unsuccessful checks* though.  :frowning_person:  
@vfdev-5 do I need to worry about warnings such as these?
Screenshot from 2020-08-29 00-48-55

**Review by vfdev-5 — APPROVED** [review]
@Tawishi PR looks good ! Let's merge it :)

About warning while building the docs, they are harmless IMO.
And yes Github CI is a bit flaky on tests of distributed computations, no worries about that.

**Comment by vfdev-5** [comment]
@Tawishi thanks for the PR ! Hope you've learnt something while working on this issue. 
If you are interested in helping with other things, please let me know.

**Comment by Tawishi** [comment]
> If you are interested in helping with other things, please let me know.

Okay, will let you know @vfdev-5

**Pull request merged**
