### PR TITLE
Skipping visdom tests on macosx

### LINKED ISSUE #2229: CI is failing with Visdom tests on macosx
## 🐛 Bug description

```
 tests/ignite/contrib/handlers/test_visdom_logger.py::test_logger_init_hostname_port ERROR [ 21%]
tests/ignite/contrib/handlers/test_visdom_logger.py::test_logger_init_env_vars FAILED [ 21%]
tests/ignite/contrib/handlers/test_visdom_logger.py::test_integration_no_executor FAILED [ 21%]
tests/ignite/contrib/handlers/test_visdom_logger.py::test_integration_with_executor FAILED [ 21%]
```

Let's temporarily disable these tests on macosx and fix them later.

- https://github.com/pytorch/ignite/pull/2201/checks?check_run_id=3730936423#step:15:201

## Environment

- PyTorch Version (e.g., 1.4):
- Ignite Version (e.g., 0.3.0):
- OS (e.g., Linux):
- How you installed Ignite (`conda`, `pip`, source):
- Python version:
- Any other relevant information:

### PR DESCRIPTION
**Pull request by theory-in-progress**
Fixes #2229

Edited the ``test_visdom_logger.py`` file to skip tests on Macosx.
 - Edited the Functions  - ``test_logger_init_hostname_port``, ``test_logger_init_env_vars``, ``test_integration_no_executor``, ``test_integration_with_executor``.

### CODE REVIEW

**Comment by theory-in-progress** [comment]
Wait.... I made a new branch from the main branch, the changes I've been making to the other branch showed up here, how? can you please advise on this @vfdev-5, should I close this Pull Request and create a new one?

**Comment by vfdev-5** [comment]
@theory-in-progress you can do the following:
```
git checkout skip_Visdom_tests_on_Macosx
git reset --hard HEAD~3
git pull origin master
git cherry-pick 7349797
git push fork skip_Visdom_tests_on_Macosx
```

**Comment by theory-in-progress** [comment]
Thanks I'll do the same and push the commit.

**Comment by sdesrozis** [comment]
It seems that the commits from #2236 still in this PR

**Comment by theory-in-progress** [comment]
@vfdev-5, does that do? is the commit okay?

**Comment by sdesrozis** [comment]
@theory-in-progress format error https://github.com/pytorch/ignite/pull/2247/checks?check_run_id=3815943853#step:11:49

**Comment by vfdev-5** [comment]
@theory-in-progress no worries.
Can you try to setup a conda environment and install everything there ?

> should I create a whole new environment of ignite from the scratch and submit a PR from a new branch?

You do not need to create a new branch. What you can do is to remove the local stuff and clone again the repository and setup your fork repository. This branch is still on your remote fork. You can fetch it and use for development.

**Comment by theory-in-progress** [comment]
I think black worked!! Please run the tests again to check if the code formatting is proper...
If this doesn't work I'll set up a conda environment and install everything there!

**Comment by vfdev-5** [comment]
@theory-in-progress I think `test_integration_with_executor_as_context_manager` is missing in your PR. Let's skip it too

**Comment by vfdev-5** [comment]
Something else is still not working with macos. Let's merge this PR and open another issue.

**Pull request merged**
