### PR TITLE
Fix for tpu test failure CI job

### PR DESCRIPTION
**Pull request by Moh-Yakoub**
Description:

All tpu tests are failing on PRs and master due to the following exception

`The following packages have unmet dependencies:
 libomp5 : Depends: libomp5-10 (>= 10~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.`

For example here https://github.com/pytorch/ignite/pull/1887/checks?check_run_id=2345750111

I am investigating if this change can fix the issue.

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by Moh-Yakoub** [comment]
Taking a look at the `Run TPU tests` I can see that it passes on the PR. So I assume the change actually fixed the issue

**Comment by vfdev-5** [comment]
@Moh-Yakoub thanks a lot for the fix ! 
I'm just curious but do not see if you've already tested to install all packages in one line:
```
sudo apt-get install -y libopenblas-dev libomp5-10 libomp5
```
?

**Comment by Moh-Yakoub** [comment]
> @Moh-Yakoub thanks a lot for the fix !
> I'm just curious but do not see if you've already tested to install all packages in one line:
> 
> ```
> sudo apt-get install -y libopenblas-dev libomp5-10 libomp5
> ```
> 
> ?

Yes I was planning to do this now, just wanted to make sure that issue was the lack of the library, now will test if running them on one line will affect the order they are installed.

**Review by vfdev-5 — APPROVED** [review]
@Moh-Yakoub LGTM, thanks for the fix !

**Pull request merged**
