### PR TITLE
setup toml, yaml, prettier in pre-commit

### PR DESCRIPTION
**Pull request by ydcjeff**
Description: setup toml, yaml, prettier in pre-commit

Check list:
* [ ] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@ydcjeff thanks for the PR and the suggestion ! I was wondering if `.pre-commit-config.yaml` is the only file that should be prettified ?

**Comment by ydcjeff** [comment]
> I was wondering if .pre-commit-config.yaml is the only file that should be prettified ?

Can you explain? pre-commit hooks format the changed files only.

**Comment by vfdev-5** [comment]
Yes, true. So, OK, once modified it will be prettified.

**Review by vfdev-5 — APPROVED** [review]
Thanks @ydcjeff for the PR !

**Comment by ydcjeff** [comment]
@vfdev-5 thank you so now .yaml, .toml will be modified once it changed.

**Pull request merged**
