### PR TITLE
Issue 1123 - Improve usage of contrib common methods with other save handlers 

### LINKED ISSUE #1123: Improve usage of contrib common methods with other save handlers
## 🚀 Feature

Currently, methods like `common.save_best_model_by_val_score` and `common.setup_common_training_handlers` work with local storage setup by `output_path`.

If we would like to use other save handlers than `DiskSaver`, it is almost impossible to use those helpers.

Idea is to be able user's setup of save handler for internal `Checkpoint` class. 
There can be several ways, I see, how to accomplish that:
- make `output_path` accept instances of `BaseSaveHandler`

```python
from ignite.contrib.engines import common

save_handler = TrainsSaver(dirname=output_path)

common.save_best_model_by_val_score(
        save_handler, evaluator, model=model, metric_name="accuracy", n_saved=3, trainer=trainer, tag="test"
)
```

- set module-wise default save handler as DiskSaver and allow user to replace it by another save hander:

```python
from ignite.contrib.engines import common

common.default_save_handler = TrainsSaver(dirname=output_path)

common.save_best_model_by_val_score(
        None, evaluator, model=model, metric_name="accuracy", n_saved=3, trainer=trainer, tag="test"
)
```

- add another argument `save_handler=None`

```python
save_handler = TrainsSaver(dirname=output_path)

common.save_best_model_by_val_score(
        None, evaluator, model=model, metric_name="accuracy", n_saved=3, trainer=trainer, tag="test", save_handler=save_handler
)
```

Any other ideas @sdesrozis @erip ?

### PR DESCRIPTION
**Pull request by vfdev-5**
Fixes #1123  

Description:
- added save_handler arg to setup_common_training_handlers
- added method delegated_save_best_models_by_val_score

Check list:
* [x] New tests are added (if a new feature is added)
* [x] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

Personally, I'm not really fan of the name `delegated_save_best_models_by_val_score`, if you have other better ideas ...

### CODE REVIEW

**Comment by vfdev-5** [comment]
@sdesrozis @erip any other better name for `delegated_save_best_models_by_val_score` ?

**Comment by sdesrozis** [comment]
Possible to do in the same way than `setup_common_training_handlers` using mutual exclusion ?

No better idea atm

**Comment by vfdev-5** [comment]
> Possible to do in the same way than `setup_common_training_handlers` using mutual exclusion ?
> 
> No better idea atm

No, due to `output_path` as first arg and not the last arg.

**Comment by vfdev-5** [comment]
@sdesrozis how about:

- `any_save_best_models_by_val_score`  ?
- `save_handler_best_models_by_val_score` ?
- `store_save_best_models_by_val_score`  (as we also have `save_best_model_by_val_score` both maybe cumbersome)
- `gen_save_best_models_by_val_score` ?

instead of `delegated_save_best_models_by_val_score`

**Comment by sdesrozis** [comment]
`save_handler_best_models_by_val_score` sounds good to me because it’s more explicit.

But I’m not a good audience for that, I never use such helpers. It encapsulates few code, I prefer write it.

**Comment by vfdev-5** [comment]
@sdesrozis i renamed the method to `gen_save_best_models_by_val_score` which looks a bit better. 

Generally, with `save_best_models_by_val_score` you can gain 5-10 lines of code when doing explicitly the same thing...
Do you think we should make provide explicit code for saving best models in reproducible examples ?

**Comment by sdesrozis** [comment]
It’s purely a matter of taste...

**Pull request merged**
