### PR TITLE
[tests] reduce `num_workers` in distributed tests

### LINKED ISSUE #1558: DataLoader worker warning in distributed tests
## 🚀 Feature
There are some of the workers warnings from `DataLoader` while running tests.
```py
tests/ignite/distributed/test_auto.py::test_auto_methods_xla
  /opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
    cpuset_checked))

---
tests/ignite/distributed/test_auto.py::test_auto_methods_xla_nprocs
  /opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
    cpuset_checked))
---
tests/ignite/distributed/test_auto.py::test_auto_methods_no_dist
tests/ignite/distributed/test_auto.py::test_auto_methods_gloo
  /usr/share/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
    cpuset_checked))
---
tests/ignite/engine/test_deterministic.py::test_update_dataloader
tests/ignite/engine/test_deterministic.py::test_resume_random_dataloader_from_epoch
tests/ignite/engine/test_deterministic.py::test_resume_random_dataloader_from_iter
tests/ignite/engine/test_deterministic.py::test_distrib_cpu
tests/ignite/engine/test_deterministic.py::test_gradients_on_resume_cpu
  /usr/share/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
    cpuset_checked))
---
tests/ignite/distributed/test_auto.py::test_auto_methods_gloo
tests/ignite/distributed/test_auto.py::test_auto_methods_gloo
  /usr/share/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 5 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
    cpuset_checked))
---
tests/ignite/engine/test_deterministic.py::test_distrib_cpu
tests/ignite/engine/test_deterministic.py::test_distrib_cpu
  /usr/share/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
    cpuset_checked))
```

### Pitch
We should reduce to maximum cpu amount of the CI.

### PR DESCRIPTION
**Pull request by ydcjeff**
Fixes #1558 

Description: reduce `num_workers` and `nproc` in distributed tests not to freeze dataloading

### CODE REVIEW

**Comment by ydcjeff** [comment]
@vfdev-5 how shall we change in circleci? through env variable? 2 workers in circleci might be bottleneck.

**Comment by vfdev-5** [comment]
Thanks for the PR!

Actually, I was thinking about reducing the number of workers for test_auto only ... Do you we have to change 4 ddp cpu workers to 2 ?

> @vfdev-5 how shall we change in circleci? through env variable? 2 workers in circleci might be bottleneck.

I'm not sure to understand your question about circleci :) Could you please detail it ?

**Comment by ydcjeff** [comment]
I think GH Action only has 2 cpus, I thought distributing with 2 cpus per process can be bottleneck. This also applies to DataLoader. so i changed it to 2.
but in circleci, windows gpu test has at least 10 cpus and linux has 16 cpus, so we should increase cpu count to speed up testing.
But that should be done in tests file or via env variables?

**Comment by vfdev-5** [comment]
> I think GH Action only has 2 cpus, I thought distributing with 2 cpus per process can be bottleneck. This also applies to DataLoader. so i changed it to 2.

Yes, GA has 2 cpus, but here in the tests I think having a small bottleneck is OK.
Let's just reduce the number of workers for test_auto for all tests without specifying on which CI it runs...

**Comment by ydcjeff** [comment]
OK, I will reduce the `num_workers` to 2 which are causing DataLoader warning and will revert everything else to normal.

**Review by vfdev-5 — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
