### PR TITLE
Fix link to pytorch documents

### PR DESCRIPTION
**Pull request by kamahori**
Fixes https://github.com/pytorch/ignite/issues/1264

Description:
I fixed broken or wrong links to `pytorch.org/docs`.

Check list:
* [ ] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [x] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
Thansk a lot for the PR @kamahori  !
Tricky part here is to update the link such that the line is not larger that 120 chars, otherwise code formatting checking fails : https://travis-ci.org/github/pytorch/ignite/jobs/727350945#L242

As far as I remember, you can drop the line like that 
```
.. _DistributedDataParallel: https://pytorch.org/docs/stable/generated/
    torch.nn.parallel.DistributedDataParallel.html
```
Please

**Comment by vfdev-5** [comment]
@kamahori have you managed to render the docs locally to verify whether the links with dropped lines are OK ?

**Comment by kamahori** [comment]
@vfdev-5 Yes, I checked. There was no problem with dropped lines.

**Comment by vfdev-5** [comment]
Thanks ! I'll merge the PR once CI is done

**Pull request merged**
