### PR TITLE
black formatted codebase with pre-commit files

### PR DESCRIPTION
**Pull request by anmolsjoshi**
Fixes # 

Description:
Per discussion on slack, added black formatting to codebase.
- Updated CONTRIBUTING.md
- Updated .travis.yml to check for black in Linting stage
- Added .pre-commit-config.yaml to invoke flake8 for linting and black for autoformatting for pre-commit hooks
- Updated tox.ini to ignore certain flake8 errors that were referenced in black documentation
    - https://black.readthedocs.io/en/stable/the_black_code_style.html#slices
    - https://black.readthedocs.io/en/stable/the_black_code_style.html#line-breaks-binary-operators
- Code base was automatically formatted using black

Helpful links:
- [Black documentation](https://black.readthedocs.io/en/stable/index.html)
- [Black playground](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ARIAmpdAD2IimZxl1N_WlkPinBFoXIfdFTaTVkGVeHShArYj9yPlDvwBA7LhGo8BvRQqDilPtgsfdKl-ha7EFp0Ma6lY_06IceKiVsJ3BpoICJM9wU1VJLD7l3qd5xTmo78LqThf9uibGWcWCD16LBOn0JK8rhhx_Gf2ClySDJtvm7zQJ1Z-Ipmv9D7I_zhjztfi2UTVsJp7917XToHBm2EoNZqyE8homtGskFIiif5EZthHQvvOj8S2gJx8_t_UpWp1ScpIsD_Xq83LX-B956I_EBIeNoGwZZPFC5zAIoMeiaC1jU-sdOHVucLJM_x-jkzMvK8Utdfvp9MMvKyTfb_BZoe0-FAc2ZVlXEpwYgJVAGdCXv3lQT4bpTXyBwDrDVrUeJEg5cXH4TUTNf-yo029ofjTcZgdwbwkBGElHbHHsQNOhuA4R9GbE2Xx6TfVmH9I4AsqU3ohV7t3GkBwkM8XInLiVOQZ4p5yjM-SW4u3I6_BUS8o2djSZaPvzZPDScXVk1OXu3w0wV7DfrgiK_dpzHntoOvqSHrNLg-Ea6zvV6G2nil3QBTBPl5PDtMwDKchtvwmlhnbvTOrh53X9EnSe8QtRKbMLO4pxx4bAJX-hVCXl5OHpCGZLowD7JdKj1-NctJy9DL99yr-X6yu7KwGCYG7t3fm-lt7Lg_HS9xbBrWDVKBKwM2F7hmR1_n9RFjznRBHD3OpHKlgiWjbWJI0Q6GhXazSt_NVH1KtFiY_UPzzuchkeq2AcjGvQd3-ZPkoFJkNU1Xx7q1i62bM0OKwmDiCfvlesDkc1kV7ClOmjkkdP1i8SGDUCylH227AAAAAD6PNxa0rsHuAAGGBckIAABcXArGscRn-wIAAAAABFla) 
- [Pre-commit documentation](https://pre-commit.com/)

Check list:
* [ ] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by anmolsjoshi** [comment]
cc @justusschock @ykumards

**Comment by vfdev-5** [comment]
Thanks @anmolsjoshi ! Huge PR with 164 updated files, if CI passes it is OK for me.
I let Justus and Yogesh to say their word too...

**Comment by justusschock** [comment]
I just got one small question: can't we use black also as a linter? This way it would be more concise than to format with black and to lint with flake and additional exceptions.

**Comment by ykumards** [comment]
> Thanks @anmolsjoshi ! Huge PR with 164 updated files, if CI passes it is OK for me.
> I let Justus and Yogesh say their word too...

love this!

**Comment by anmolsjoshi** [comment]
@justusschock black is primarily a code formatter. We can simply invoke it with a --check flag to check if all the files in the code base comply with, but it doesn't suggest what should be changed. Please see below.

```python
black . --check
would reformat /home/joshi/ignite/tests/ignite/metrics/test_metric.py
would reformat /home/joshi/ignite/tests/ignite/metrics/test_accuracy.py
would reformat /home/joshi/ignite/tests/ignite/metrics/test_precision.py
would reformat /home/joshi/ignite/tests/ignite/metrics/test_recall.py
Oh no! 💥 💔 💥
165 files would be reformatted, 19 files would be left unchanged.
```

**Pull request merged**
