### PR TITLE
[skip ci] Doctests for `MeanAbsoluteError` and `MeanSquaredError`

### PR DESCRIPTION
**Pull request by DevPranjal**
Addresses #2265 

Description: Added doctests for `MeanAbsoluteError` and `MeanSquaredError`

Check list:

- [x] New tests are added (if a new feature is added)
- [x] New doc strings: description and/or example code are in RST format
- [x] Documentation is updated (if required)

### CODE REVIEW

**Comment by sdesrozis** [comment]
@DevPranjal Thank you ! It looks good to me.

**Comment by DevPranjal** [comment]
> Please add `[skip ci]` to avoid the ci tests as only the doctests should be triggered.
Should I add it in the title of the PR?

**Comment by DevPranjal** [comment]
The coverage issues don't seem related to this PR. Are they?

**Comment by Ishan-Kumar2** [comment]
> Partially fixes #2265

@DevPranjal in the PR description having "fixes" next to issue number will cause the issue to close on merging this PR. Maybe change it for something like "Addresses"?

**Pull request merged**
