### PR TITLE
Enable Github CI

### PR DESCRIPTION
**Pull request by justusschock**
Adds GitHub Action to Test on CPU for all Python versions

Fixes #658 
cc @vfdev-5 

Have a look at https://github.com/justusschock/ignite/actions/runs/33776965 for an example run

### CODE REVIEW

**Comment by vfdev-5** [comment]
@justusschock looks great! 

What do you think about removing smoke tests of examples? I thinks we can have only unit tests.

**Comment by justusschock** [comment]
I think, I would leave these examples, they are not consuming that much time (compared to the unit tests)

**Comment by vfdev-5** [comment]
Yes, they take ~4.3min. Well, let's keep them.

**Comment by vfdev-5** [comment]
I have no idea how to configure now Github Actions from yaml. Interface proposes only to create from scratch or prebuilt things, but no options from existing yaml.
Also there is no way to remove old removed Actions... :(

**Pull request merged**
