### PR TITLE
Updated docker images

### PR DESCRIPTION
**Pull request by vfdev-5**
Description:
- pytorch -> 1.7.0-cuda11.0-cudnn8

### CODE REVIEW

**Comment by vfdev-5** [comment]
@fco-dv I tried naively update docker images but there are few problems with building them. CI's error can be ignored right now, the main issue I also encounter locally is while building apex flavored images due to default python version change 3.7 -> 3.8
```
Created wheel for apex: filename=apex-0.1-cp38-cp38-linux_x86_64.whl size=11164150 sha256=f31d244a61229fb8b6e8e28edd0d4469bb74daa438b521ad1ce79c6c68eb5bcd

....

Step 7/13 : COPY --from=apex-builder /tmp/apex/apex-0.1-cp37-cp37m-linux_x86_64.whl apex-0.1-cp37-cp37m-linux_x86_64.whl                                    
COPY failed: stat /var/lib/docker/overlay2/46037488d5ab47c47ba230133989b324b69bbb865c5c7c309723f579152c5718/merged/tmp/apex/apex-0.1-cp37-cp37m-linux_x86_64.whl: no such fi
le or directory                          
```

**Comment by fco-dv** [comment]
@vfdev-5 sure I'll check that and update the PR accordingly

**Review by fco-dv — CHANGES_REQUESTED** [review]
Added suggestions to fix apex flavored images builds. Local builds are ok for apex, hvd-apex and msdp-apex-base.

**Comment by vfdev-5** [comment]
Can not build on GitHub Actions : 
```
Error processing tar file(exit status 1): write /opt/conda/pkgs/cache/18414ddb0.json: no space left on device
```

**Pull request closed without merging**
