### PR TITLE
[DO NOT MERGE] code-style debugging

### PR DESCRIPTION
**Pull request by trsvchn**
PR to test code-style workflow behavior on forked repos

### CODE REVIEW

**Comment by vfdev-5** [comment]
@trsvchn thanks for testing that! Let me enable code-formatting GA for that.

**Comment by trsvchn** [comment]
ok, that was a test push with fork actions enabled

upstream workflow fails
but fork workflow pushes autopep8 fix, interesting...

**Comment by trsvchn** [comment]
well, smth new:
https://github.com/pytorch/ignite/runs/1946964559#step:5:49

Looks like upstream workflow fails but fork's workflow pushes fine

going to disable fork actions

**Comment by trsvchn** [comment]
I 've tried everything? but still:

> remote: Permission to pytorch/ignite.git denied to github-actions[bot].

**Comment by vfdev-5** [comment]
@trsvchn thanks for investigating that. Probably, we have to search at `stefanzweifel/git-auto-commit-action@v4` source repo if there is something could be done with that...

**Comment by trsvchn** [comment]
@vfdev-5 It Works!!

**Comment by vfdev-5** [comment]
@trsvchn maybe we should disable pull_request option ? It still fails: https://github.com/pytorch/ignite/runs/1978982689

**Comment by trsvchn** [comment]
@vfdev-5 Yes, I was thinking about that. But, how to handle cases with non-fork PRs? How often do we have them?

**Comment by vfdev-5** [comment]
Well, they can be only created by maintainers so i'd say it is OK to ignore them now.

**Comment by vfdev-5** [comment]
I also wonder why this autopep thing can not restart completely all CI tests, currently there are only 3 are shown...

**Comment by trsvchn** [comment]
yeah, that makes sense, we can comment out them and waiting until GH team will fix double triggering :)
Anyway, push event will be active so, it is not a big loss

**Comment by trsvchn** [comment]
> I also wonder why this autopep thing can not restart completely all CI tests, currently there are only 3 are shown...

huh, looks like a new opportunity to learn)

**Comment by vfdev-5** [comment]
> > I also wonder why this autopep thing can not restart completely all CI tests, currently there are only 3 are shown...
> 
> huh, looks like a new opportunity to learn)

Let's take a break for a moment with that :)

**Comment by trsvchn** [comment]
@vfdev-5 testing pr-labeler

**Comment by trsvchn** [comment]
Oh, its not a good example since there are no matching files in PR

**Comment by vfdev-5** [comment]
labeler works actually, see here : https://github.com/pytorch/ignite/pull/1733

**Pull request closed without merging**
