### PR TITLE
Add replace outdated example with a simpler one and add gitignore

### PR DESCRIPTION
**Pull request by keon**
WIP PR 

- [x] add .gitignore to ignore files generated in examples
- [x] add simplest example mnist.py 
- [ ] fix the lint error
- [ ] add the new version of mnist_with_visdom.py 
- [ ] allow examples to be tested automatically

Reference Issue
#53

### CODE REVIEW

**Comment by fmassa** [comment]
@keon any updates on this? Maybe it might be better to hold on on this until #54 is merged?

**Comment by alykhantejani** [comment]
Hi @keon,

Thanks for the PR. I have a few comments:
1) I think we should keep the `mnis_with_visdom` example, even though its more complex it shows how to integrate with visdom (and tensorboard is also coming - see #60)

2) However, I do agree a simple vanilla mnist example would probably be very helpful

3) I'm not sure the .gitignore is needed, there seems to be a lot of references to file types not present in the repo.

Could you update this PR to just be the new mnist example?

**Comment by keon** [comment]
Hey, @fmassa and @alykhantejani,
Thanks for the comment.

I agree with the comments and like @fmassa said, I think it is best to wait for the major PR #54 before updating this one.

**Comment by alykhantejani** [comment]
hi @keon #54 has now been merged. Would you be able to update the plain mnist example?

**Comment by keon** [comment]
sure, ill work on it today.

**Comment by alykhantejani** [comment]
Closing in favor of #96

**Pull request closed without merging**
