### PR TITLE
Add pr_target as a new code-style workflow triggering event

### PR DESCRIPTION
**Pull request by trsvchn**
Possible fix to #1660 

Description:

Adding new type event, as recommended here: [Using the Action in forks from public repositories](https://github.com/stefanzweifel/git-auto-commit-action#using-the-action-in-forks-from-public-repositories)

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@trsvchn thanks for the PR. Let's try here to make it commit to the fork on a code-format broken file. Maybe, such that we could see all of that in the action.
- Let's create a unformatted file (that we can finally remove).
- enable GA on your fork and commit to the PR -> We should see it fixing the broken file.
- disable GA on your fork and commit again to the PR originally broken file -> Normally, we should not see any failure with "Format python code / code-style (pull_request)"...

**Comment by trsvchn** [comment]
1. Fork's GH Actions is on.
2. Committing broken file.

**Comment by trsvchn** [comment]
1. Fork's GH Actions is off.
2. Committing broken file once again.

**Comment by vfdev-5** [comment]
@trsvchn thanks ! Looks like there is no way to make it work if GA are disabled on fork ?

**Comment by trsvchn** [comment]
@vfdev-5 yep :(

**Comment by trsvchn** [comment]
@vfdev-5 I think this is related to this:

> The permissions for the GITHUB_TOKEN in forked repositories is read-only. 

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories-2

But in August 2020 they add pull_request_target that is granted a read/write repository token

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target

Looks, like it requires more research

**Comment by vfdev-5** [comment]
Thanks for digging it up @trsvchn ! 

> Looks, like it requires more research

As you wish. Maybe, we can simply postpone on this issue and just disable code-style action for some moment...

**Comment by vfdev-5** [comment]
Maybe, we can simply add the following condition `if: github.event.pull_request.head.repo.full_name == github.repository` when push action happens ?

**Comment by trsvchn** [comment]
> Maybe, we can simply add the following condition `if: github.event.pull_request.head.repo.full_name == github.repository` when push action happens ?
> 
> Such that the action wont push and wont fail and if there is code-formatting issue it will be still reported by other actions.

Yeah, let's try it!

But anyway, I will continue that investigation :)

**Comment by vfdev-5** [comment]
Sounds great, thanks !

**Comment by vfdev-5** [comment]
Interesting idea @trsvchn ! Actually, how about instead of showing what to fix we could say:
1) either enable local GA
2) or install and run what we suggest in CONTRIBUTING
What do you think ?

Btw, I wonder how 121 chars line in ignite/metrics/psnr.py passed all previous checks ?

**Comment by trsvchn** [comment]
> Btw, I wonder how 121 chars line in ignite/metrics/psnr.py passed all previous checks ?

@vfdev-5 Haha)) Yeah I was surprised as well)

> Actually, how about instead of showing what to fix we could say (post a message or in the code...):

Sure, that makes sense, we can raise a single error in actions log, I will prepare another demo :)

**Comment by vfdev-5** [comment]
> Sure, that makes sense, we can raise a single error in actions log, I will prepare another demo :)

Or maybe, post a comment in the PR ?

**Comment by trsvchn** [comment]
I am not sure that we can do that from the a workflow, and again not sure that event from the fork has a permission for that, I will check.

**Comment by trsvchn** [comment]
> GitHub does not allow GitHub Actions running from a forked repo to modify parent repo, even to post comments on its own PR.

**Comment by vfdev-5** [comment]
Yes, this seems correct. But here it is our own action running on our PR ... Actually, I think I have seen bots like that saying that the code is not correctly formatted and suggesting what to do ...

**Comment by trsvchn** [comment]
@vfdev-5 Oh, yeah!  I think they have a kind of contributor access or smth, and use gh API for commenting and labeling.

**Comment by trsvchn** [comment]
@vfdev-5 I think we can try similar approach to make a POST request from the workflow

**Comment by vfdev-5** [comment]
OK, let's try that

**Comment by trsvchn** [comment]
@vfdev-5 I have great news! I think I finally hacked `pull_request_target` (At least for my sandbox repo)!

Screenshot from 2021-02-25 13-26-23

The trick is that `pull_request_target` really works, but it doesn't start in PRs from forks that modify or create workflow file.

> ... instead of running against the workflow and code from the merge commit, the event runs against the workflow and code from the base of the pull request. This means the workflow is running from a trusted source and is given access to a read/write token as well as secrets enabling the maintainer to safely comment on or label a pull request.

So, to enable fork events we need first to merge modified `code-style.yml` with `pull_request_target` enabled. Like I did here: https://github.com/trsvchn/gha-sandbox/pull/2

After that we can accept and handle PRs from the community)

https://github.com/trsvchn/gha-sandbox/pull/3

**Comment by vfdev-5** [comment]
Sounds great ! Thanks a lot for digging into that, hope this could be helpful for you as well ! 
So, current version of our `code-style.yml` is OK or you think to update it to a finalized version ?

**Comment by trsvchn** [comment]
@vfdev-5 Yes, it is, it's very helpful. 

yeah, I think `code-style.yml` is ready, I've tested this configuration in sandbox and it works. So we can start with this setup, anyway we can test it only after the merge)

**Comment by vfdev-5** [comment]
OK, so I can merge it to the master and we'll see. So, current failure of `Format python code / code-style (pull_request)` is acceptable, right ?

**Comment by trsvchn** [comment]
Yes, you are right! I have similar failure for `pull_request` event

**Review by vfdev-5 — APPROVED** [review]
Thanks @trsvchn !

**Comment by trsvchn** [comment]
@vfdev-5 I reopened this https://github.com/pytorch/ignite/pull/1663 to see what happens

**Pull request merged**
