### PR TITLE
Added Checkpoint.get_default_score_fn

### PR DESCRIPTION
**Pull request by vfdev-5**
Description:
- Added Checkpoint.get_default_score_fn to simplify best_model_handler creation
- Added missing docs refs to handlers.rst

Check list:
* [x] New tests are added (if a new feature is added)
* [x] New doc strings: description and/or example code are in RST format
* [x] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@sdesrozis can you review this PR ?

**Comment by sdesrozis** [comment]
I will do it soon.

**Review by sdesrozis — APPROVED** [review]
LGTM !! 

A remark, what do you think to introduce a sign argument somewhere to handle the case when best score is the smallest value ? Typically when your metric is related to a loss score.

**Comment by vfdev-5** [comment]
Yes, makes sense! Will update this PR

**Review by sdesrozis — APPROVED** [review]
Thank you for the update !!

**Pull request merged**
