### PR TITLE
Notebook Example - Variational Auto Enconders on MNIST

### LINKED ISSUE #367: Add some notebooks in examples
> Putting tutorials like the basic mnist into Jupyter notebooks would be helpful for new users to get started quicker

### PR DESCRIPTION
**Pull request by anmolsjoshi**
Fixes #367 

Description:
Provide example in the form of Jupyter Notebook for using VAE on MNIST.

Check list:
* [ ] New tests are added (if a new feature is modified)
* [ ] New doc strings: text and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@anmolsjoshi could you please integrate the features from this [message](https://github.com/pytorch/ignite/issues/446#issuecomment-466965501):
- plot KL divergence and reconstruction loss separately

**Comment by anmolsjoshi** [comment]
@vfdev-5 I'll work on this tonight.

**Comment by anmolsjoshi** [comment]
@vfdev-5 I added some plots, let me know if that's ok. I can edit as needed.

**Comment by vfdev-5** [comment]
@anmolsjoshi looks good! Just some nits on functions and classes in the text without `function`. And there is a commented line  `# Loss(loss_function).attach(evaluator, 'loss')` which we can remove if useless...

And why KLD loss grows ?

**Comment by anmolsjoshi** [comment]
KLD increasing was curious - I saw this explanation [here](https://www.reddit.com/r/MachineLearning/comments/6m2tje/d_kl_divergence_decreases_to_a_point_and_then/)

Thoughts?

cc @alykhantejani

**Comment by vfdev-5** [comment]
Tested on 50 epochs with a large batch_size, same behaviour.

Another question, what is the purpose of 
```
trainer_history = {'bce': [], 'kld': [], 'loss': []}
```

**Comment by anmolsjoshi** [comment]
> Another question, what is the purpose of
> trainer_history = {'bce': [], 'kld': [], 'loss': []}
> It seems it is not used...

@vfdev-5 My bad, I had it there to plot trainer history.

What are your thoughts on creating a History handler, this way we could store all the metrics per epoch. If anything, I could update this notebook to show an example of how to create a handler and use it. Thoughts?

**Comment by vfdev-5** [comment]
> What are your thoughts on creating a History handler, this way we could store all the metrics per epoch. If anything, I could update this notebook to show an example of how to create a handler and use it. Thoughts?

I'm not sure that this is useful outside jupyter notebooks scope. In general case history is "stored" by the logger, e.g. logged to the screen, or in a plot like TB/Visdom etc.

**Comment by anmolsjoshi** [comment]
@vfdev-5 understood. 

After the deletion of train_history and some added description of the plots, is there anything else that is needed?

**Comment by vfdev-5** [comment]
@anmolsjoshi I think it is OK except nits of notebook rendering:
- put variables, functions, classes as `variables`, `functions`, `classes`
then we can merge it.

**Comment by anmolsjoshi** [comment]
@vfdev-5 I've updated the notebooks by fixing the rendering, running the notebook for more epochs, adding a small blurb before the plot. 

please review and merge.

**Comment by vfdev-5** [comment]
@anmolsjoshi nice colors :)
Thanks, I'll merge it, now

**Comment by vfdev-5** [comment]
@anmolsjoshi I thought that we could add some words about the notebooks in the docs ?

**Comment by anmolsjoshi** [comment]
@vfdev-5 good idea, i'll send in a commit in a few minutes.

**Pull request merged**
