### PR TITLE
Docker for users with MSDeepSpeed

### PR DESCRIPTION
**Pull request by fco-dv**
- msdp-base | vision | nlp

Fixes # 

Description:
Docker for users with MSDeepSpeed.

DeepSpeed built version is :
``bash
root@95582039fc68:/workspace# python -c "import deepspeed; print(deepspeed.__version__)"
0.3.0+c66f388
``
Images sizes : 
```
REPOSITORY                      TAG                             IMAGE ID            CREATED             SIZE
pytorchignite/msdp-vision       latest                          6fc2aae1295a        4 minutes ago       4.62GB
pytorchignite/msdp-nlp          latest                          c74e6339da3c        10 minutes ago      4.13GB
pytorchignite/msdp-base         latest                          94fa400910d3        14 minutes ago      4GB
```

Check list:
* [ ] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@fco-dv looks awesome ! Nit: as apex is implicit inside deepspeed I was wondering whether we shouldn't call them `msdp-apex-*` ?

**Review by vfdev-5 — APPROVED** [review]

**Comment by fco-dv** [comment]
thx for your review @vfdev-5 !,  yes it will be more relevant to change to `msdp-apex-* ` .

**Comment by vfdev-5** [comment]
@fco-dv please push the images to hub.docker

**Comment by fco-dv** [comment]
Tags latest and 1.6-0.4.1 are pushed, dockerhub repos description are updated

**Comment by vfdev-5** [comment]
@fco-dv thanks a lot !

**Pull request merged**
