### PR TITLE
Fix GPU tests because of missing .cpu()

### PR DESCRIPTION
**Pull request by sdesrozis**
Related to #2490

Description:

Missing cpu() to use numpy() on Tensors

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by sdesrozis** [comment]
You mean I create a branch in the ignite repo and I push the fix inside ? Or maybe there is a smarter way to do that using a relevant git command line ?

**Comment by vfdev-5** [comment]
yes, just do the following, assuming the `origin` points to `https://github.com/pytorch/ignite`
```
git push origin fix_gpu_precision_recall_curve
```

**Comment by sdesrozis** [comment]
It seems I can't rerun workflow from CircleCI...

**Comment by vfdev-5** [comment]
Let's skip circle ci, if `Run unit tests on GPUs / gpu-tests (push)` passes we can merge this PR.

**Comment by vfdev-5** [comment]
@sdesrozis tests are stuck on `tests/ignite/contrib/metrics/test_precision_recall_curve.py::test_distrib_nccl_gpu`

**Comment by vfdev-5** [comment]
Looks like real. I'll cancel the job and check later what happens.

**Pull request merged**
