### PR TITLE
Simple fix for #373

### PR DESCRIPTION
**Pull request by TheCodez**
Is this enough or should we also check if 'to' is a method?

### CODE REVIEW

**Comment by vfdev-5** [comment]
@TheCodez thanks for the PR, but #373 is more subtle than that. Traced/Scripted models has attribute `to` as they derive from `nn.Module`:
```python
hasattr(traced_model, "to"), hasattr(scripted_model, "to")
> (True, True)
```

Probably one can trace a model when its on GPU and would like to run it on a data being on GPU...
We need to think about all these cases

**Comment by TheCodez** [comment]
> RuntimeError: to is not supported on TracedModules

Instead of checking if we have the `to` method, we should probably just check if the model passed in is a `ScriptModule`.

**Comment by vfdev-5** [comment]
@TheCodez yes, we can differentiate whether model is `ScriptModule` or not with `isinstance`.

> In that case we should warn the user, if the device is different from the one of the traced model, right?

I'm not sure if we can get the device of the traced/scripted model...

Another point to confirm, can we train traced/scripted models ? Otherwise we should raise an error if `ScriptModule` is passed to `create_supervised_trainer`.

**Comment by TheCodez** [comment]
According to https://github.com/pytorch/pytorch/issues/14696 they can be trained

**Comment by TheCodez** [comment]
I did some changes, which for now just throws a `RuntimeException `if a device is passed when using traced modules.

**Comment by TheCodez** [comment]
Closing this as it should be solved when https://github.com/pytorch/pytorch/pull/15340 is merged.

**Pull request closed without merging**
