### PR TITLE
Updated pr-labeler-config.yml to v5

### PR DESCRIPTION
**Pull request by avinashsharma080**
Description: Updated .github/pr-labeler-config.yml to version v5

Check list:

- [x] New tests are added (if a new feature is added)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@avinashsharma080 thanks for the PR, let's also update [triage.yml](https://github.com/pytorch/ignite/blob/master/.github/workflows/triage.yml) according to https://github.com/actions/labeler?tab=readme-ov-file#create-workflow

**Comment by avinashsharma080** [comment]
Do I have to make separate PR to check new commits?

**Comment by vfdev-5** [comment]
No, update this PR

**Review by vfdev-5 — APPROVED** [review]
Thanks @avinashsharma080

**Pull request merged**
