### PR TITLE
ClearMLLogger: add older Trains SDK backwards compatibility

### PR DESCRIPTION
**Pull request by jkhenning**
Description:
Add backwards-compatibility so that users who still use older Trains SDK packages can still use the ClearMLLogger (formerly TrainsLogger).
Tested using `mnist_with_clearml_logger.py`.
Obviously, any test explicitly importing `clearml` will neither be affected nor will support backwards compatibility.
Runtime errors were kept as-is since there's no reason to instruct users to install anything but the latest ClearML SDK in case it is required.

Check list:
* [ ] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Review by vfdev-5 — COMMENTED** [review]
Thanks for the PR @jkhenning !
Could you please add the following to mypy.ini
```
[mypy-trains.*]
ignore_missing_imports = True
```
as it was previously (https://github.com/pytorch/ignite/commit/2485fd42c6ef4d3e97fd606a52f8c6e5d940357e#diff-6f2d4ba9ca9a357d31014946667b7bed1bfdbc6d2530afc77778fa0a36bee457). Otherwise mypy is failing.

**Comment by jkhenning** [comment]
Sure @vfdev-5 , my bad for missing that 🙂

**Review by vfdev-5 — APPROVED** [review]
Thanks @jkhenning ! Looks good !

**Review by ydcjeff — APPROVED** [review]
Thank you @jkhenning LGTM too

**Pull request merged**
