### PR TITLE
Fixes #289

### LINKED ISSUE #289: [Feature Request]  tqdm_logger update on every epoch instead of every iteration
Currently `tqdm_logger` creates a progress bar for every epoch and updates it on every iteration. I would like to have a single progress bar for the entire run that updates every epoch instead.

### PR DESCRIPTION
**Pull request by vfdev-5**
Fixes #289  

Description: 
Updated `ProgressBar.attach` API by adding supplementary args: 
- `event_name=Events.ITERATION_COMPLETED`
- `closing_event_name=Events.EPOCH_COMPLETED)`
to handle demanded use-case:
```python
    n_epochs = 10
    loader = [1, 2, 3, 4, 5]
    engine = Engine(update_fn)

    pbar = ProgressBar()
    pbar.attach(engine, event_name=Events.EPOCH_STARTED, closing_event_name=Events.COMPLETED)
    engine.run(loader, max_epochs=n_epochs)
    # expected = u'Epoch: [9/10]  90%|█████████  [00:00<00:00]'
```

- **Custom events are not supported yet !**
  - We need to order base events and custom events to  prevent the cases where closing event happens before logging event
  - It is not evident how to compute length of progress bar with custom events and number of total custom events...

Check list:
* [x] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
DO NOT MERGE YET. Forgot about #391

**Comment by vfdev-5** [comment]
@drozzy you can check out this version if it works better for you.
Keep in mind that tqdm_notebook has some issue with the layout in some cases: https://github.com/tqdm/tqdm/issues/649

**Comment by vfdev-5** [comment]
@anmolsjoshi OK, I'll update the notebooks ASAP

**Comment by vfdev-5** [comment]
@anmolsjoshi I updated TextCNN and docstring. Rendering of progressbar in the github is not better.
Just `HBox ...` however inside jupyter notebook we can see the widgets etc... We can leave it like this, IMO

**Comment by drozzy** [comment]
@vfdev-5 Sorry I haven't used ignite in a while so I can't actually reproduce it. Is there a minimal working example that I can use to test this?

**Comment by vfdev-5** [comment]
@drozzy check this one:
```python
import torch
import time

from ignite.engine import Engine, Events
from ignite.contrib.handlers import ProgressBar

def update(engine, batch):
    time.sleep(0.5)

def run(data):
    trainer = Engine(update)
    ProgressBar(persist=True, bar_format="").attach(trainer)
    trainer.run(data, max_epochs=2)

data = [1] * 10
run(data)
```

**Pull request merged**
