### PR TITLE
Fix Pypi nightly releases

### PR DESCRIPTION
**Pull request by Evpok**
Picked up from #599

### CODE REVIEW

**Comment by vfdev-5** [comment]
@Evpok may I ask you to check this manually on `test.pypi.org` : https://test.pypi.org/project/pytorch-ignite/ ? 
If you have an account on test.pypi I can add you as maintainer and you can try to upload a binary with this new version and check the installation with `--pre`...

**Comment by Evpok** [comment]
Sure my handle there is evpok as well

**Comment by vfdev-5** [comment]
@Evpok done ! Added your handle as maintainer.

**Comment by Evpok** [comment]
It seems to work

**Comment by Evpok** [comment]
Let's hope it's for good this time !

**Comment by vfdev-5** [comment]
Live-stream : https://travis-ci.org/pytorch/ignite/builds/580213934

**Comment by vfdev-5** [comment]
Same problem
```
HTTPError: 400 Client Error: '0.2.0.dev0+20190903' is an invalid value for Version. Error: Can't use PEP 440 local versions. See https://packaging.python.org/specifications/core-metadata for url: https://upload.pypi.org/legacy/
PyPI upload failed.
```

**Comment by Evpok** [comment]
Okay I found it but I am confused: I messed up the sed line in travis, it should have been `sed -i "s/__version__ = '\(.*\)'/__version__ = '\1.dev$(date -u +%Y%m%d)'/g" ignite/__init__.py` (with a single plus instead of two) OTOH, I don't understand the extra `0`. I will test it on my fork, sorry for the trouble

**Comment by vfdev-5** [comment]
Thank you @Evpok, 

Following PEP-440 on [local versions](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers), it seems it can be everything user wants...
About `dev0` it is OK, following public version ids: `[N!]N(.N)*[{a|b|rc}N][.postN][.devN]`, see [here](https://www.python.org/dev/peps/pep-0440/#public-version-identifiers).

**Comment by Evpok** [comment]
Yes, but if pypi doesn't accept it… I think it's best if ignite nightly use the same template as pytorch

**Comment by vfdev-5** [comment]
Sounds good!

**Pull request merged**
