### PR TITLE
Format small

### LINKED ISSUE #1496: Replace string .format with f-string
## 🚀 Feature

Once #1495 is merged we can replace all `.format` with f-strings.

If interested in helping with the issue, please comment here and send a PR according to our contributing guide.
Feel free to ask questions for details if needed.

### PR DESCRIPTION
**Pull request by uribgp**
Fixes #1496

Description: Breaking up large pull

Check list:
* [ ] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by uribgp** [comment]
There is one file remaining, unfortunately I'm a bit stuck on it.  
```
        output_message = """
 ----------------------------------------------------
| Time profiling stats (in seconds):                 |
 ----------------------------------------------------
total  |  min/index  |  max/index  |  mean  |  std

Processing function:
{processing_stats}

Dataflow:
{dataflow_stats}

Event handlers:
{total_time:.5f}

- Events.STARTED: {STARTED_names}
{STARTED}

- Events.EPOCH_STARTED: {EPOCH_STARTED_names}
{EPOCH_STARTED}

- Events.ITERATION_STARTED: {ITERATION_STARTED_names}
{ITERATION_STARTED}

- Events.ITERATION_COMPLETED: {ITERATION_COMPLETED_names}
{ITERATION_COMPLETED}

- Events.EPOCH_COMPLETED: {EPOCH_COMPLETED_names}
{EPOCH_COMPLETED}

- Events.COMPLETED: {COMPLETED_names}
{COMPLETED}
""".format(
            processing_stats=odict_to_str(results["processing_stats"]),
            dataflow_stats=odict_to_str(results["dataflow_stats"]),
            **others,
        )
```

I'm confused on how to break up the **others.  



There are several lines which are similar to:
`
row[3] = "{}/{}".format(*row[3])  # type: ignore[misc]
`
I tried to do it f"{row[3][0]}/{row[3][1]}" 
`
but it was returning errors.

**Comment by vfdev-5** [comment]
@uribgp let's keep `format` here. There is nothing wrong to use it there.

**Comment by uribgp** [comment]
OK.  In that case this should be the final pull.  I'll check why these are failing.

**Comment by vfdev-5** [comment]
Please, set `Fixes #1496` in the description then and once this PR is merged it will autoclose the issue. And we can also close the large PR.

**Review by vfdev-5 — APPROVED** [review]
Looks good ! Thanks a lot for such a huge work, @uribgp !
I was just wondering if you could rerun jupyter notebooks after the modification ?

**Comment by uribgp** [comment]
I didn't try to run all of the cells, just the ones I edited.  It seemed to be working though.  

Thanks for all the help with this!

**Comment by vfdev-5** [comment]
> I didn't try to run all of the cells, just the ones I edited. It seemed to be working though.

Sounds good !

**Pull request merged**
