### PR TITLE
ignite.handlers: removed type annotations from docstring

### PR DESCRIPTION
**Pull request by vfdev-5**
Partly addresses #1665 

Description:
- ignite.handlers: removed type annotations from docstring
- fixed missing docstring

Check list:

- [ ] New tests are added (if a new feature is added)
- [x] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

cc @ydcjeff for a review :)

### CODE REVIEW

**Comment by ydcjeff** [comment]
- https://deploy-preview-1672--pytorch-ignite-preview.netlify.app/handlers.html#ignite.handlers.Timer.attach
- https://deploy-preview-1672--pytorch-ignite-preview.netlify.app/handlers.html#ignite.handlers.global_step_from_engine

> one to which Checkpoint handler is added.

- https://deploy-preview-1672--pytorch-ignite-preview.netlify.app/handlers.html#ignite.handlers.Checkpoint.get_default_score_fn

**Comment by vfdev-5** [comment]
@ydcjeff should be good now

**Comment by ydcjeff** [comment]
https://deploy-preview-1672--pytorch-ignite-preview.netlify.app/_modules/ignite/handlers/timing.html#Timer.attach
still needs to remove here, the rest looks good

**Comment by vfdev-5** [comment]
> https://deploy-preview-1672--pytorch-ignite-preview.netlify.app/_modules/ignite/handlers/timing.html#Timer.attach
> still needs to remove here, the rest looks good

Oh, that's right, should have missed that somehow. Thanks a lot for pointing out!

**Pull request merged**
