### PR TITLE
Add missing classes and links for engine docs

### LINKED ISSUE #1459: Master engine docs missing something
## 🐛 Bug description

Latest master engine docs is missing some classes under `Engine` class, I believe.
Also `CallableEventWithFilter` link is not working.

Screen Shot 2020-11-12 at 20 13 22

### PR DESCRIPTION
**Pull request by trsvchn**
Fixes #1459 

Description:

Add missing classes from `engine` module, fix link for `CallableEventWithFilter`

Check list:
* [ ] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@trsvchn thanks for the quick fix ! I was wondering if we could improve more the text around this TOC such that
```
ignite.engine
==============

Main module of the library contains the following structures:
.. currentmodule:: ignite.engine.engine

.. autosummary::
    :nosignatures:
    :autolist:

and

.. currentmodule:: ignite.engine.events

.. autosummary::
    :nosignatures:
    :autolist:

with, in addition, few helper methods for deterministic training

.. currentmodule:: ignite.engine.deterministic

.. autosummary::
    :nosignatures:
    :autolist:

and helper methods to define supervised trainer and evaluator:

.. currentmodule:: ignite.engine

.. autosummary::
    :nosignatures:
    :autolist-functions:
```


It would be perfect to add some info to `CallableEventWithFilter` docstring that user normally haven't use this class but inherit from `EventEnum` if needed.

**Review by vfdev-5 — APPROVED** [review]
thanks a lot @trsvchn , ignite's doc master :)

**Comment by trsvchn** [comment]
@vfdev-5 Sorry, didn't see your comments and new suggestions about docs, was very busy on the weekend, I see that a lot of work has been done these days, going to catch up everything :)

**Comment by vfdev-5** [comment]
@trsvchn no problems at all :) This weekend we had PyData Global mentored sprint and a lot of other contributions

**Comment by trsvchn** [comment]
@vfdev-5 Oh, that's great! :)

**Pull request merged**
