### PR TITLE
Fix #192 setting the model on specified device if not None

### LINKED ISSUE #192: create_supervised_trainer fails if model device is diff from arg device
Feature or bug to discuss. If I modify `mnist.py` example: 
```python
def run(train_batch_size, val_batch_size, epochs, lr, momentum, log_interval):
    train_loader, val_loader = get_data_loaders(train_batch_size, val_batch_size)
    model = Net()
    device = 'cpu'

    if torch.cuda.is_available():
        device = 'cuda'
#         model = model.to(device)

    optimizer = SGD(model.parameters(), lr=lr, momentum=momentum)
    trainer = create_supervised_trainer(model, optimizer, F.nll_loss, device=device)
    evaluator = create_supervised_evaluator(model,
                                            metrics={'accuracy': CategoricalAccuracy(),
                                                     'nll': Loss(F.nll_loss)},
                                            device=device)
```
The operation `model(x)` will fail as `x` and `model` are on different devices. Maybe we need to : 
-  check this and assert or
-  remove `device` from argument and setup it internally according to the model or
- set model on the provided `device` 

@alykhantejani @elanmart @jasonkriss  What do you guys think about ?

### PR DESCRIPTION
**Pull request by vfdev-5**
Also tested on a local machine with GPU

@elanmart if you could take a look

### CODE REVIEW

**Comment by jasonkriss** [comment]
👍 Looks good!

**Comment by elanmart** [comment]
@vfdev-5 LGTM, but perhaps we'd want to remove https://github.com/pytorch/ignite/blob/master/examples/mnist.py#L53 ?

**Comment by vfdev-5** [comment]
@elanmart Nice catch, yes we can remove `model = model.to(device)` from examples.

Concerning a note in the doc, I think we can keep it like that and avoid docs regeneration PR :)
If you guys think if it is necessary I can do it...

**Comment by elanmart** [comment]
> Concerning a note in the doc, I think we can keep it like that and avoid docs regeneration PR :)

My vote would still go to adding the note :) But hey, who am I to decide -- @alykhantejani ?

**Comment by vfdev-5** [comment]
@elanmart every vote is counted in ignite autocracy :)

**Pull request merged**
