### PR TITLE
Update test generation in `test_accuracy`

### PR DESCRIPTION
**Pull request by KickItLikeShika**
Update the way we generate tests in `test_accuracy`

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Review by vfdev-5 — APPROVED** [review]
Looks good, thanks @KickItLikeShika !

I'll merge it after fixing the issue with `fixed_dirname`: https://github.com/pytorch/ignite/pull/1831

**Comment by KickItLikeShika** [comment]
@vfdev-5 i guess those CI failures can be ignored, right?

**Comment by vfdev-5** [comment]
Yes, they are unrelated but very annoying :(
I wonder if we can repro them locally...

**Comment by KickItLikeShika** [comment]
@vfdev-5 sure i will look into it, any details i need to know?

**Pull request merged**
