### PR TITLE
Updating Fast Neural Style Example

### PR DESCRIPTION
**Pull request by anmolsjoshi**
Updated Progress Bar in Fast Neural Style Example

Description:
Integrated Progress Bar from ignite.contrib.handlers to example.

### CODE REVIEW

**Comment by anmolsjoshi** [comment]
@vfdev-5 maybe this needs to be moved to `examples/contrib` just as `mnist_with_tqdm_logger.py` has been.

**Comment by vfdev-5** [comment]
@anmolsjoshi yes, I think so

**Comment by anmolsjoshi** [comment]
@vfdev-5 I moved the example, similarly i think dcgan.py needs to be moved also, as it uses tqdm_logger.py and we need to add a smoke_test for the mnist_with_tqdm_logger.py.

**Comment by vfdev-5** [comment]
Actually I have doubt now. The first idea was to provide some examples which use `contrib` module. No smoke tests as it will become too heavy. However I would also like to keep base dcgan and fast neural style tutorial in offical non-contrib examples. 
In case of `mnist_with_tqdm_logger.py`, this one is a copy of `mnist.py` + adaptions.
If we just move fast neural style to contrib this will look like a regression...

**Comment by miguelvr** [comment]
@vfdev-5 why not move the `ProgressBar` out of contrib?

**Comment by vfdev-5** [comment]
@miguelvr this was another idea (not exposed in the previous message) which requires to add a new dependency to ignite. Need to discuss about this. Especially, in the very beginning we thought about that some helpful stuff could migrate from contrib to core. Today there is still one issue on progressbar to solve and probably this will take time to confirm the API ...

**Comment by miguelvr** [comment]
what is the issue?

**Comment by anmolsjoshi** [comment]
@vfdev-5 should i close this PR until #289 is resolved?

**Pull request closed without merging**
