### PR TITLE
Set tqdm version in CI as <=4.48.0

### LINKED ISSUE #1287: Set tqdm version in CI as <=4.48.0
## 🐛 Bug description

Currently, the CI is broken due to recent changes of tqdm v4.49.0 :
- https://travis-ci.org/github/pytorch/ignite/jobs/726808846#L4137

Idea is to fix tqdm's version to v4.48.0 for all CI here: 
- https://github.com/pytorch/ignite/blob/master/requirements-dev.txt#L9

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at CONTRIBUTING guide.

### PR DESCRIPTION
**Pull request by benji011**
Fixes #1287

Description:
These changes is to just set `tqdm` to be `v4.48.0` only.

Check list:
* [ ] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Review by vfdev-5 — APPROVED** [review]
Thanks @benji011 !

**Comment by vfdev-5** [comment]
@benji011 I edited a bit PR's message, you can see the diff, it is just for correct association between issue and PR...

**Comment by benji011** [comment]
@vfdev-5 Ah, thank you! Sorry i should've checked other PRs for reference

**Comment by vfdev-5** [comment]
@benji011 no worries about that :)

**Comment by vfdev-5** [comment]
@benji011 there is an issue with pytorch-nightlies: conda installs pytorch 1.3.1 instead of 1.7 nightly. It is out of our scope, so 
nothing to do about that.

**Pull request merged**
