### PR TITLE
#1615 : add check_opencv function in 'build_all.sh' for 'vision' . 

### LINKED ISSUE #1615: ImportError: libGL.so.1: cannot open shared object file
## 🐛 Bug description

Using pytorchignite/hvd-apex-vision

```
python -c "import cv2"
> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

Same for vision and apex-vision images:
```
docker run --rm -it pytorchignite/apex-vision python -c "import cv2"
docker run --rm -it pytorchignite/vision python -c "import cv2"
```

## Environment

 - PyTorch Version (e.g., 1.4):
 - Ignite Version (e.g., 0.3.0):
 - OS (e.g., Linux):
 - How you installed Ignite (`conda`, `pip`, source):
 - Python version:
 - Any other relevant information:

cc @fco-dv

### PR DESCRIPTION
**Pull request by vfdev-5**
Fixes #1615

Original PR: #1628 

Switch to 'opencv-python-headless'. (#1628)

Co-authored-by: vfdev <vfdev.5@gmail.com>

Fixes #{issue number}

Description:

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@fco-dv probably, the check as you did are not working: 
```
Successfully tagged pytorchignite/hvd-vision:latest
./hvd/build_all.sh: 69: [[: not found
./hvd/build_all.sh: 69: hvd-vision: not found
```
https://app.circleci.com/pipelines/github/pytorch/ignite/1358/workflows/d21bbba3-d96b-443d-b365-10c592dc85b7/jobs/3864/parallel-runs/0/steps/0-102

**Comment by fco-dv** [comment]
was running the script with `bash hvd/build_all.sh` on my local machine, seems like this fix should work with   `sh ./hvd/build_all.sh` :
```
    if [ ${image_name} = "hvd-vision" ] || [ ${image_name} = "hvd-apex-vision" ]; then
        check_opencv "pytorchignite/${image_name}:latest"
    fi
```

**Comment by vfdev-5** [comment]
@fco-dv I think it would be better to run all those checks in a python script as suggested #1644. 

In the current PR, msdp is still missing right ?

**Comment by fco-dv** [comment]
yes that's right for msdp

**Comment by vfdev-5** [comment]
@sdesrozis please do not update this PR as it trigger new docker images build :) to much computations for nothing

**Comment by sdesrozis** [comment]
Sorry 😢

**Pull request merged**
