### PR TITLE
Merge of EpochMetric in _BaseRegressionEpoch

### PR DESCRIPTION
**Pull request by sdesrozis**
Related to #967 

Description:

Merge `EpochMetric` in `_BaseRegressionEpoch`.

Introduction of a parameter to define the usage of metric : "regression" or "classification"

Check list:
* [ ] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@sdesrozis could you please review ?

**Comment by vfdev-5** [comment]
OK, `_BaseRegressionEpoch` inherits from `_BaseRegression` in order to benefit of `_check_shape` and `_check_type` methods (later I forgot to put in `_BaseRegression`). We may either define those methods externally and call them separately in each class, so that `_BaseRegressionEpoch` wont inherit from `_BaseRegression`. Another way is to define another base class for this two methods and make everything like
```
class _BaseBaseRegression:
    # define _check_shape, _check_type

class _BaseRegression(_BaseBaseRegression, Metric):
    # ...

class _BaseRegressionEpoch(_BaseBaseRegression, EpochMetric):
    # ...
```
and no diamonds.

**Comment by sdesrozis** [comment]
Aggregation means use objects in class (« has a » concept) rather than inheritance (« is a » concept). Recall that I talk about code factorisation. Using external methods to share code is on the same line than aggregation.

I agree the 2 alternatives you listed, and I prefer to do not use inheritance here.

**Comment by vfdev-5** [comment]
@sdesrozis please take a look

**Comment by sdesrozis** [comment]
Perfect !!

**Pull request merged**
