### PR TITLE
Refactor PSNR and SSIM

### PR DESCRIPTION
**Pull request by sadra-barikbin**
- `compute` method returns `float` in PSNR and SSIM as it does in other metrics.
- Refactor tests in PSNR
- Refactor tests in SSIM

### CODE REVIEW

**Comment by vfdev-5** [comment]
@sadra-barikbin can you provide PR description with the info we decided in discord.

**Comment by vfdev-5** [comment]
Let's also swtich SSIM back to float as well

**Review by vfdev-5 — APPROVED** [review]
Thanks, LGTM!

However we need to fix horovod tests which are skipped right now:
```
tests/ignite/metrics/test_psnr.py::test_distrib_input_float[horovod] SKIPPED (Skip if no Horovod dist support) [ 86%]
```
https://github.com/pytorch/ignite/actions/runs/3654919549/jobs/6175755766#step:9:1770

**Comment by sadra-barikbin** [comment]
Don't you merge it?

**Pull request merged**
