### PR TITLE
Add --color=yes in pytest config

### PR DESCRIPTION
**Pull request by ydcjeff**
Description: Add --color=yes in pytest config for easier to find FAILED tests

Check list:
* [ ] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@ydcjeff thanks for the PR ! Could you please show an example of how it looks like ?

**Comment by ydcjeff** [comment]
@vfdev-5 It's already in the CI logs of this PR. You can look at there. It will show in green color if tests are passing and starts to show in red if one test starts to fail.

**Comment by vfdev-5** [comment]
OK, I see. It is relevant for github actions. In travis and circle ci is already colored. Thanks !

**Review by vfdev-5 — APPROVED** [review]
LGTM!

**Pull request merged**
