### PR TITLE
fix: add `py.typed` for type checkers

### PR DESCRIPTION
**Pull request by ydcjeff**
See [colab](https://colab.research.google.com/drive/1TjFg53UfdwR7__2qjRGCJ4Be0emwWsPT?usp=sharing).

Description:

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
For context:
- https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages
- https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/

**Comment by ydcjeff** [comment]
> Can you also add a test step similar to the one you have in the colab ?

I think this is not needed once we confirm it is working.

**Comment by vfdev-5** [comment]
> > Can you also add a test step similar to the one you have in the colab ?
> 
> I think this is not needed once we confirm it is working.

There will be also failure for other domain libs like torchvision. OK for keeping this PR without test step.

Saw that MONAI does the same: https://github.com/Project-MONAI/MONAI/pull/626

**Review by vfdev-5 — APPROVED** [review]
Thanks @ydcjeff !

**Pull request merged**
