### PR TITLE
Improve CI configuration #1269

### LINKED ISSUE #1269: Improve CI configuration
## 🚀 Feature

For github acitons we can set a tag to trigger workflow run depending on modified files:
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-paths

Idea is to add those tags to our github CI yaml such that we do not trigger the workflow if, for example, `*.md` is modified etc.

Nice to have : 
- find a similar feature for circle-ci and travis ci if any
- add to the corresponding configuration file.

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at [CONTRIBUTING guide](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md).

### PR DESCRIPTION
**Pull request by rexdivakar**
Fixes #1269 

Description:

Check list:
* [x] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by rexdivakar** [comment]
Please validate it and approve my PR @vfdev-5

**Comment by vfdev-5** [comment]
@rexdivakar thanks for the PR ! Let's improve it by setting up the following rule:
- we ignore all github actions if modifications are in the following folders or files:
   - assets
   - docker
   - conda.recipe
   - *.md
- same should be applied for circle ci and travis configs

**Comment by rexdivakar** [comment]
Will update and revert back !

**Comment by rexdivakar** [comment]
Will this issue be updated for hacktoberfest ? @vfdev-5

**Comment by vfdev-5** [comment]
@rexdivakar can you work on this PR and update according to https://github.com/pytorch/ignite/pull/1367#issuecomment-704096314. Thanks

**Comment by rexdivakar** [comment]
Yes been trying to test my changes that's the delay will update soon

**Comment by vfdev-5** [comment]
@rexdivakar any updates on this PR ?

**Comment by rexdivakar** [comment]
I'm having issues with Travis CI setup i will debug it and ping u back soon

**Comment by rexdivakar** [comment]
I have completed the Github actions but testing travis and Circle CI is a challenging task and taking time, if u want i can add those changes apart from Circle and Travis !! @vfdev-5

**Comment by vfdev-5** [comment]
@rexdivakar can you detail the issues with Travis and Circle CI ? Have you checked their docs on that ?

> I have completed the Github actions but testing travis and Circle CI is a challenging task and taking time

No, unfortunately, even for Github actions your PR does not accomplish requested task (see https://github.com/pytorch/ignite/pull/1367#issuecomment-704096314). To have this PR approved and merged it has to contain
- filters for Github Actions as required above
- filters for Travis CI
- filters for Circle CI
Let me know if you interested in working on the issue.

**Comment by rexdivakar** [comment]
Give me sometime to crack it and will raise a PR will all the changes as u needed ! @vfdev-5  Hope that works for u ?

**Comment by vfdev-5** [comment]
OK, let's keep it open for couple of days more.

**Comment by vfdev-5** [comment]
Unfortunately, have to close it as stale.

**Pull request closed without merging**
