### PR TITLE
Fix GPU failures (#1881)

### PR DESCRIPTION
**Pull request by vfdev-5**
Original PR #1881 

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Comment by vfdev-5** [comment]
@KickItLikeShika if tests are passing here, let's apply the same trick to other tests of median related metrics.

**Comment by KickItLikeShika** [comment]
@vfdev-5 unfortunately it didn't work..

**Comment by KickItLikeShika** [comment]
I found the error!  we did `np_res_prepend = 100.0 * np.median(e)` but it should be np_res_prepend = 100.0 * np.median(e_prepend)

**Comment by KickItLikeShika** [comment]
@vfdev-5 It works fine now, thanks for providing such inspiring ideas! Thanks for your help!

**Pull request merged**
