### PR TITLE
Rouge last details

### PR DESCRIPTION
**Pull request by gucifer**
Added a new test for multireference value check.
Added RougeN and RougeL to docs.
Check list:

- [x] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [x] Documentation is updated (if required)

### CODE REVIEW

**Comment by gucifer** [comment]
@vfdev-5 can you check the issue with docs? They are the same old docs but they seem to be failing the linkcheck test

**Comment by vfdev-5** [comment]
I think this should be related to https://github.com/pytorch/ignite/issues/1787
cc @ydcjeff

**Comment by ydcjeff** [comment]
According to the error message
```
ignite.metrics.rouge.RougeL.rst:35:<autosummary>:1:py:obj reference target not found: ignite.metrics.rouge.RougeL.compute_score
```
`compute_score` of `RougeL` doesn't have a docstring while docs is trying to include that method.

**Comment by vfdev-5** [comment]
Thanks a lot @ydcjeff ! 
@sdesrozis , @gucifer I was also wondering if those methods should be necessarily public ? Otherwise, let's put them private and thus no need to support them...

**Comment by gucifer** [comment]
> Thanks a lot @ydcjeff !
> @sdesrozis , @gucifer I was also wondering if those methods should be necessarily public ? Otherwise, let's put them private and thus no need to support them...

Simple Rouge class will apply a training sample on all the metrics for which it is instantiated but if you wish to manually update only one metric this is a way to do so. Also, similarly metric_name is to find which object in Rouge is for which exact rouge metric.

**Comment by vfdev-5** [comment]
I would say that `metric_name` can private. I understand its usage inside Rouge but If I instantiate `m = RougeL`, I'm not sure that I'll call `m.metric_name()` to get the class name.
If we keep `compute_score`, we have to explain the difference vs `compute` method.

**Comment by gucifer** [comment]
> I would say that `metric_name` can private. I understand its usage inside Rouge but If I instantiate `m = RougeL`, I'm not sure that I'll call `m.metric_name()` to get the class name.
> If we keep `compute_score` public, we have to explain the difference vs `compute` method.

I will make them private then. Also, it is asking docs for pretty much every class, please check on that.

**Comment by vfdev-5** [comment]
But I agree that every public class should be documented, otherwise put it private.

**Comment by gucifer** [comment]
> But I agree that every public class should be documented, otherwise put it private. That's new module added by Jeff is called `nitpicky` :)

I will make everything private tomorrow if that's fine by you.

**Comment by sdesrozis** [comment]
@gucifer Why this PR has so much commits ? 

Could you create a clean PR from a fresh new branch created from master ? It means you would have to first merge the upstream master in your fork master before create a new branch. Therefore, merged `rouge` will be in your new branch.

Thanks !

**Pull request closed without merging**
